#!/usr/bin/env bash
# Run the full local verification matrix:
#   - plain build + unit tests + lint (flow tests skip via build tag)
#   - lint with the rewire build tag so the flow test files are covered
#   - flow tests via ./script/test, which auto-installs rewire and
#     uses a separate GOCACHE so toolexec'd artifacts stay isolated
#     from the production build cache
set -euo pipefail

go build -o /dev/null ./...
go test ./...
golangci-lint run ./...
golangci-lint run --build-tags=rewire ./...
./script/test ./...
