package browser

import (
	"github.com/go-rod/rod"
	"github.com/stretchr/testify/require"
	"github.com/tofutools/tclaude/internal/backend/app"
	"github.com/tofutools/tclaude/internal/backend/model"
	"testing"
)

func TestBrowserTeamEditorAuthorsRosterWavesBriefingsAndReopens(t *testing.T) {
	ctx, page, operator := processEditorBrowser(t)
	page.MustElement("[data-tab=processes]").MustClick()
	page.MustElementR("#definition-list button", "^New team template$").MustClick()
	page.MustElement("[aria-label='Team template name']").MustSelectAllText().MustInput("Review team")
	for _, member := range []struct{ key, name string }{{"builder", "Builder"}, {"reviewer", "Reviewer"}} {
		page.MustElementR("#team-editor button", "^Add member$").MustClick()
		page.MustElement("#team-editor [name=key]").MustInput(member.key)
		page.MustElement("#team-editor [name=name]").MustInput(member.name)
		page.MustElement("#team-editor [name=role_label]").MustInput(member.key)
		page.MustElement("#team-editor [name=description]").MustInput("Literal <b>member description</b>")
		page.MustElement("#team-editor [name=harness]").MustSelect("codex")
		page.MustElement("#team-editor [name=model]").MustInput("fixture-model")
		page.MustElement("#team-editor [name=effort]").MustInput("high")
		page.MustElement("#team-editor [name=cwd]").MustInput("/tmp")
		page.MustElement("#team-editor [name=owner]").MustClick()
		page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	}
	page.MustElementR("#team-editor nav button", "^Waves$").MustClick()
	page.MustElementR("#team-editor button", "^Add wave$").MustClick()
	page.MustElement("#team-editor [name=id]").MustInput("review")
	page.MustElement("#team-editor [name=maxWait]").MustSelectAllText().MustInput("123")
	page.MustElement("#team-editor [name=members]").MustSelect("Reviewer")
	page.MustElement("#team-editor [name=after]").MustSelect("initial")
	page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	page.MustElementR("#team-editor nav button", "^Briefings$").MustClick()
	page.MustElementR("#team-editor button", "^Add briefing$").MustClick()
	page.MustElement("#team-editor [name=id]").MustInput("review-brief")
	page.MustElement("#team-editor [name=body]").MustInput("Review {{mission}} and report concrete findings.")
	page.MustElement("#team-editor [name=syntax]").MustSelect("Expand {{task}} and {{mission}}")
	require.NoError(t, page.MustElement("#team-editor [name=members]").Select([]string{"Builder"}, false, rod.SelectorTypeText))
	page.MustElement("#team-editor [name=members]").MustSelect("Reviewer")
	page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	page.MustElementR("#team-editor nav button", "^Workspace and phases$").MustClick()
	page.MustElement("#team-editor [name=workspace]").MustSelect("Separate member workspaces")
	page.MustElement("#team-editor [name=phases]").MustInput("Implement\nReview")
	page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	page.MustElementR("#team-editor button", "^Edit Review$").MustClick()
	page.MustElement("#team-editor [name=phase_roles]").MustInput("all")
	page.MustElement("#team-editor [name=criteria]").MustInput("Inspect the diff <literally> and record findings.")
	page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	page.MustElementR("#team-editor nav button", "^Parameters$").MustClick()
	page.MustElementR("#team-editor button", "^Add parameter$").MustClick()
	page.MustElement("#team-editor [name=name]").MustInput("release_key")
	page.MustElement("#team-editor [name=display_name]").MustInput("Release label")
	page.MustElement("#team-editor [name=doc]").MustInput("Literal team parameter help")
	page.MustElement("#team-editor [name=type]").MustSelect("number")
	page.MustElement("#team-editor [name=default]").MustInput("0.1234567890123456789")
	page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	page.MustElementR("#team-editor button", "^Save team revision$").MustClick()
	page.MustElementR("#team-editor-status", "Revision 1 · saved")
	var definitions []model.Definition
	require.NoError(t, operator.Call(ctx, "GET", "/v2/definitions", nil, &definitions))
	require.Len(t, definitions, 1)
	var result app.DefinitionResult
	require.NoError(t, operator.Call(ctx, "GET", "/v2/definitions/"+string(definitions[0].ID), nil, &result))
	require.Equal(t, "0.1234567890123456789", string(result.Revision.Parameters[0].Default))
	team := result.Revision.Team
	require.Len(t, team.Members, 2)
	require.Equal(t, model.AgentLabels{Role: "reviewer", Description: "Literal <b>member description</b>"}, team.Members[1].Labels)
	require.True(t, team.Members[0].Owner)
	require.True(t, team.Members[1].Owner)
	require.Equal(t, "high", team.Members[1].Desired.Effort)
	require.Len(t, team.Waves, 2)
	require.True(t, team.Waves[0].WaitForIdle)
	require.True(t, team.Waves[1].WaitForIdle)
	require.Equal(t, int64(123), team.Waves[1].MaxWaitSeconds)
	require.Len(t, team.Briefings, 1)
	require.Equal(t, "mission-v1", team.Briefings[0].Syntax)
	require.Equal(t, "Review {{mission}} and report concrete findings.", team.Briefings[0].Body)
	require.Equal(t, []string{"review-brief"}, team.Members[1].BriefingIDs)
	require.Empty(t, team.Members[0].BriefingIDs)
	require.Equal(t, []string{"builder"}, team.Waves[0].MemberKeys)
	require.Equal(t, []string{"initial"}, team.Waves[1].DependsOn)
	require.Equal(t, []string{"reviewer"}, team.Briefings[0].MemberKeys)
	require.Equal(t, model.WorkspacePolicyPerMember, team.WorkspacePolicy)
	require.Equal(t, []model.TeamPhase{{Name: "Implement", Roles: []string{}}, {Name: "Review", Roles: []string{"all"}, Criteria: "Inspect the diff <literally> and record findings."}}, team.AdvisoryProcess)
	require.Empty(t, team.AdvisoryPhases)
	page.MustElementR("#team-editor button", "^Close team editor$").MustClick()
	page.MustElementR("#definition-list button", "^Edit team template$").MustClick()
	page.MustElementR("#team-editor nav button", "^Workspace and phases$").MustClick()
	page.MustElementR("#team-editor button", "^Edit Review$").MustClick()
	require.Equal(t, "all", page.MustElement("#team-editor [name=phase_roles]").MustProperty("value").Str())
	require.Equal(t, "Inspect the diff <literally> and record findings.", page.MustElement("#team-editor [name=criteria]").MustProperty("value").Str())
	page.MustElementR("#team-editor nav button", "^Parameters$").MustClick()
	page.MustElementR("#team-editor button", "^Edit release_key$").MustClick()
	require.Equal(t, "Literal team parameter help", page.MustElement("#team-editor [name=doc]").MustProperty("value").String())
	require.Equal(t, "0.1234567890123456789", page.MustElement("#team-editor [name=default]").MustProperty("value").Str())
	page.MustElement("#team-editor [name=display_name]").MustSelectAllText().MustInput("Updated release label")
	page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	page.MustElementR("#team-editor nav button", "^Members$").MustClick()
	page.MustElementR("#team-editor button", "^Edit Reviewer$").MustClick()
	require.Equal(t, "reviewer", page.MustElement("#team-editor [name=role_label]").MustProperty("value").Str())
	require.Equal(t, "Literal <b>member description</b>", page.MustElement("#team-editor [name=description]").MustProperty("value").Str())
	require.Equal(t, "fixture-model", page.MustElement("#team-editor [name=model]").MustProperty("value").Str())
	require.Equal(t, "high", page.MustElement("#team-editor [name=effort]").MustProperty("value").Str())
	require.True(t, page.MustElement("#team-editor [name=owner]").MustProperty("checked").Bool())
	page.MustElement("#team-editor [name=key]").MustSelectAllText().MustInput("checker")
	page.MustElementR("#team-editor button", "^Apply changes$").MustClick()
	page.MustElementR("#team-editor button", "^Save team revision$").MustClick()
	page.MustElementR("#team-editor-status", "Revision 2 · saved")
	require.NoError(t, operator.Call(ctx, "GET", "/v2/definitions/"+string(definitions[0].ID), nil, &result))
	require.Equal(t, []string{"checker"}, result.Revision.Team.Waves[1].MemberKeys)
	require.Equal(t, "0.1234567890123456789", string(result.Revision.Parameters[0].Default))
	require.Equal(t, "release_key", result.Revision.Parameters[0].Name)
	require.Equal(t, "Updated release label", result.Revision.Parameters[0].DisplayName)
	require.Equal(t, "Literal team parameter help", result.Revision.Parameters[0].Doc)
	require.Equal(t, []string{"checker"}, result.Revision.Team.Briefings[0].MemberKeys)
	page.MustElementR("#team-editor button", "^Close team editor$").MustClick()
	require.False(t, page.MustElement("#error").MustVisible())
}
