package harness

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/tofutools/tclaude/pkg/claude/common/convops"
	"github.com/tofutools/tclaude/pkg/claude/common/db"
)

// Gemini CLI's cold conversation store.
//
// The layout is read from the upstream source at GeminiPinnedVersion
// (packages/core/src/config/storage.ts, projectRegistry.ts and
// services/chatRecordingService.ts), not from documentation:
//
//	<GEMINI_CLI_HOME or $HOME>/.gemini/
//	    projects.json                       {"projects": {"<abs project root>": "<slug>"}}
//	    tmp/<slug>/.project_root            the project root this slug belongs to
//	    tmp/<slug>/chats/session-<YYYY-MM-DDTHH-MM>-<id[:8]>.jsonl
//	    tmp/<slug>/chats/<parent-id>/<id>.jsonl   subagent transcripts (not conversations)
//
// A session file is JSONL. Its first line is a metadata record (sessionId,
// projectHash, startTime, lastUpdated, kind, …); every later line is one of
//
//   - a message record ({"id": …, "type": "user"|"gemini"|"info"|…,
//     "content": …}); a repeated id REPLACES the earlier record in place
//   - {"$set": {…}} — a metadata update (summary, lastUpdated, a whole
//     `messages` checkpoint, …), merged over the metadata
//   - {"$rewindTo": "<id>"} — drops that message and everything after it
//     (an unknown id drops every message)
//
// A resume APPENDS to the same file. Older CLIs wrote one pretty-printed
// `.json` record per session; resuming one of those migrates it to a sibling
// `.jsonl` without deleting the original, so one session id can own two files
// — Gemini keeps the one with the later lastUpdated, and so does this store.
//
// Which sessions count as conversations is Gemini's own rule, mirrored so that
// tclaude never lists a conversation `gemini --resume <id>` would refuse: a
// session must be a main (non-subagent) session with at least one RESUMABLE
// message (sessionUtils.getAllSessionFiles + isResumableMessageRecord).
//
// Gemini has no user-settable title. Its `summary` is generated by the CLI and
// maps onto SessionEntry.Summary; a tclaude rename is kept in tclaude's own
// conv_index overlay (SetTitle) and surfaced as CustomTitle, so DisplayTitle's
// existing precedence (custom title over summary over first prompt) applies.

const (
	geminiDirName          = ".gemini"
	geminiTmpDirName       = "tmp"
	geminiChatsDirName     = "chats"
	geminiProjectRootFile  = ".project_root"
	geminiProjectsFileName = "projects.json"
	geminiSessionPrefix    = "session-"

	// GeminiHomeEnvVar relocates the directory Gemini CLI treats as the user's
	// home (packages/core/src/utils/paths.ts homedir()).
	GeminiHomeEnvVar = "GEMINI_CLI_HOME"
)

// geminiHome returns the directory Gemini CLI treats as home: GEMINI_CLI_HOME
// when set, otherwise the OS home. Empty when neither resolves.
func geminiHome() string {
	if home := strings.TrimSpace(os.Getenv(GeminiHomeEnvVar)); home != "" {
		return filepath.Clean(home)
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return home
}

// geminiDir returns <home>/.gemini, or "" when no home resolves.
func geminiDir() string {
	home := geminiHome()
	if home == "" {
		return ""
	}
	return filepath.Join(home, geminiDirName)
}

type geminiConvStore struct {
	// dir overrides the <home>/.gemini resolution. Empty means "resolve
	// normally"; tests set it to a fixture root.
	dir string
}

var _ ConvStore = geminiConvStore{}

func (s geminiConvStore) root() (string, error) {
	dir := s.dir
	if dir == "" {
		dir = geminiDir()
	}
	if dir == "" {
		return "", errors.New("gemini: cannot determine the Gemini CLI home directory")
	}
	return dir, nil
}

// ListConvs assembles one SessionEntry per Gemini session. An empty cwd lists
// every project; a non-empty one is matched through symlinks (copilotCwdFilter,
// whose reasoning applies unchanged: Gemini records process.cwd(), which is
// already physical).
//
// A single unreadable or malformed session file is skipped with a warning, not
// fatal — Gemini writes these files while tclaude reads them. Only a failure to
// enumerate the tmp directory itself is an error.
func (s geminiConvStore) ListConvs(cwd string) ([]convops.SessionEntry, error) {
	entries, err := s.scan()
	if err != nil {
		return nil, err
	}
	// Synced over the UNFILTERED listing, for the reason Copilot's store
	// gives: a cwd-scoped sync must not make the cache flip its contents
	// depending on where the last command ran.
	syncGeminiConvIndex(entries)
	if cwd != "" {
		filter := newCopilotCwdFilter(cwd)
		filtered := entries[:0]
		for _, entry := range entries {
			if filter.matches(entry.ProjectPath) {
				filtered = append(filtered, entry)
			}
		}
		entries = filtered
	}
	sort.SliceStable(entries, func(i, j int) bool {
		if entries[i].Modified != entries[j].Modified {
			return entries[i].Modified > entries[j].Modified
		}
		return entries[i].SessionID < entries[j].SessionID
	})
	return entries, nil
}

// scan reads every project's chats directory and returns one deduplicated entry
// per conversation, without touching tclaude's cache.
func (s geminiConvStore) scan() ([]convops.SessionEntry, error) {
	root, err := s.root()
	if err != nil {
		return nil, err
	}
	tmpDir := filepath.Join(root, geminiTmpDirName)
	projectDirs, err := os.ReadDir(tmpDir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return []convops.SessionEntry{}, nil
		}
		return nil, fmt.Errorf("gemini: read %s: %w", tmpDir, err)
	}
	registry := readGeminiProjectRegistry(root)

	bestByID := map[string]convops.SessionEntry{}
	for _, projectDir := range projectDirs {
		if !projectDir.IsDir() {
			continue
		}
		slugDir := filepath.Join(tmpDir, projectDir.Name())
		projectRoot := geminiProjectRoot(slugDir, projectDir.Name(), registry)
		if projectRoot == "" {
			// A legacy hash-named directory Gemini has not migrated yet, or
			// one with no ownership marker: without a project root the
			// conversation cannot be resumed (Gemini scopes --resume to the
			// cwd's project), so it is not listed.
			continue
		}
		chatsDir := filepath.Join(slugDir, geminiChatsDirName)
		files, err := os.ReadDir(chatsDir)
		if err != nil {
			if !errors.Is(err, fs.ErrNotExist) {
				slog.Warn("gemini convstore: chats directory unreadable; project skipped",
					"path", chatsDir, "error", err)
			}
			continue
		}
		for _, file := range files {
			name := file.Name()
			if file.IsDir() || !geminiIsSessionFile(name) {
				continue
			}
			entry, ok := readGeminiSessionFile(filepath.Join(chatsDir, name), projectRoot)
			if !ok {
				continue
			}
			if prior, seen := bestByID[entry.SessionID]; seen && prior.Modified >= entry.Modified {
				continue
			}
			bestByID[entry.SessionID] = entry
		}
	}
	entries := make([]convops.SessionEntry, 0, len(bestByID))
	for _, entry := range bestByID {
		entries = append(entries, entry)
	}
	return entries, nil
}

func geminiIsSessionFile(name string) bool {
	return strings.HasPrefix(name, geminiSessionPrefix) &&
		(strings.HasSuffix(name, ".jsonl") || strings.HasSuffix(name, ".json"))
}

// readGeminiProjectRegistry returns projects.json inverted (slug → root). It is
// only the fallback for a slug directory missing its .project_root marker; an
// unreadable or malformed registry is an empty map, not an error.
func readGeminiProjectRegistry(root string) map[string]string {
	raw, err := os.ReadFile(filepath.Join(root, geminiProjectsFileName))
	if err != nil {
		return nil
	}
	var registry struct {
		Projects map[string]string `json:"projects"`
	}
	if json.Unmarshal(raw, &registry) != nil {
		return nil
	}
	inverted := make(map[string]string, len(registry.Projects))
	for projectRoot, slug := range registry.Projects {
		inverted[slug] = projectRoot
	}
	return inverted
}

// geminiProjectRoot returns the project a slug directory belongs to. The
// directory's own .project_root marker wins — it is what Gemini itself checks
// before reusing a slug (ProjectRegistry.verifySlugOwnership) — and the
// registry is consulted only when the marker is absent.
func geminiProjectRoot(slugDir, slug string, registry map[string]string) string {
	if raw, err := os.ReadFile(filepath.Join(slugDir, geminiProjectRootFile)); err == nil {
		if root := strings.TrimSpace(string(raw)); root != "" {
			return filepath.Clean(root)
		}
	}
	if root := registry[slug]; root != "" {
		return filepath.Clean(root)
	}
	return ""
}

// geminiMessage is the subset of one message record the store needs.
type geminiMessage struct {
	ID         string          `json:"id"`
	Type       string          `json:"type"`
	Content    json.RawMessage `json:"content"`
	Model      string          `json:"model"`
	ToolCalls  []any           `json:"toolCalls"`
	Thoughts   []any           `json:"thoughts"`
	resumable  bool
	isUser     bool
	userPrompt string
}

// geminiMetadata is the subset of the metadata record (and of $set updates)
// the store needs.
type geminiMetadata struct {
	SessionID   string `json:"sessionId"`
	ProjectHash string `json:"projectHash"`
	StartTime   string `json:"startTime"`
	LastUpdated string `json:"lastUpdated"`
	Summary     string `json:"summary"`
	Kind        string `json:"kind"`
}

// geminiSession accumulates one session file the way loadConversationRecord
// does.
type geminiSession struct {
	meta     geminiMetadata
	messages []geminiMessage
	index    map[string]int
}

func newGeminiSession() *geminiSession {
	return &geminiSession{index: map[string]int{}}
}

// mergeMeta overlays the non-empty fields of one metadata record or $set.
func (g *geminiSession) mergeMeta(raw json.RawMessage) {
	var m geminiMetadata
	if json.Unmarshal(raw, &m) != nil {
		return
	}
	if m.SessionID != "" {
		g.meta.SessionID = m.SessionID
	}
	if m.ProjectHash != "" {
		g.meta.ProjectHash = m.ProjectHash
	}
	if m.StartTime != "" {
		g.meta.StartTime = m.StartTime
	}
	if m.LastUpdated != "" {
		g.meta.LastUpdated = m.LastUpdated
	}
	if m.Summary != "" {
		g.meta.Summary = m.Summary
	}
	if m.Kind != "" {
		g.meta.Kind = m.Kind
	}
}

// putMessage inserts a message record, or replaces an earlier record with the
// same id in place (a JS Map's set() keeps the original insertion order).
func (g *geminiSession) putMessage(raw json.RawMessage) {
	var msg geminiMessage
	if json.Unmarshal(raw, &msg) != nil || msg.ID == "" {
		return
	}
	text := geminiContentText(msg.Content)
	switch msg.Type {
	case "user":
		msg.isUser = true
		msg.resumable = !geminiIgnoredUserContent(strings.TrimSpace(text))
		msg.userPrompt = strings.TrimSpace(text)
	case "gemini":
		msg.resumable = strings.TrimSpace(text) != "" || len(msg.ToolCalls) > 0 || len(msg.Thoughts) > 0
	}
	if at, ok := g.index[msg.ID]; ok {
		g.messages[at] = msg
		return
	}
	g.index[msg.ID] = len(g.messages)
	g.messages = append(g.messages, msg)
}

// rewind drops the message with the given id and everything after it, or every
// message when the id is unknown — exactly loadConversationRecord's rule.
func (g *geminiSession) rewind(id string) {
	at, ok := g.index[id]
	if !ok {
		at = 0
	}
	for _, msg := range g.messages[at:] {
		delete(g.index, msg.ID)
	}
	g.messages = g.messages[:at]
}

// replaceMessages handles a `$set.messages` checkpoint: the message list is
// rebuilt from the provided array.
func (g *geminiSession) replaceMessages(raw json.RawMessage) {
	var msgs []json.RawMessage
	if json.Unmarshal(raw, &msgs) != nil {
		return
	}
	g.messages = nil
	g.index = map[string]int{}
	for _, msg := range msgs {
		g.putMessage(msg)
	}
}

// applyRecord folds one decoded line into the session, in the same precedence
// loadConversationRecord uses: rewind, message, metadata update, metadata.
func (g *geminiSession) applyRecord(line []byte) {
	var record map[string]json.RawMessage
	if json.Unmarshal(line, &record) != nil {
		return
	}
	if raw, ok := record["$rewindTo"]; ok {
		var id string
		if json.Unmarshal(raw, &id) == nil {
			g.rewind(id)
		}
		return
	}
	if raw, ok := record["id"]; ok {
		var id string
		if json.Unmarshal(raw, &id) == nil {
			g.putMessage(line)
			return
		}
	}
	if set, ok := record["$set"]; ok {
		var fields map[string]json.RawMessage
		if json.Unmarshal(set, &fields) == nil {
			if msgs, ok := fields["messages"]; ok {
				g.replaceMessages(msgs)
			}
		}
		g.mergeMeta(set)
		return
	}
	g.mergeMeta(line)
	// A legacy single-line record carries its messages inline.
	if msgs, ok := record["messages"]; ok {
		g.replaceMessages(msgs)
	}
}

// readGeminiSessionFile builds one entry from a session file, or reports false
// when the file is not a listable conversation.
func readGeminiSessionFile(path, projectRoot string) (convops.SessionEntry, bool) {
	file, err := os.Open(path)
	if err != nil {
		if !errors.Is(err, fs.ErrNotExist) {
			slog.Warn("gemini convstore: session file unreadable; skipped", "path", path, "error", err)
		}
		return convops.SessionEntry{}, false
	}
	defer func() { _ = file.Close() }()
	info, err := file.Stat()
	if err != nil {
		return convops.SessionEntry{}, false
	}

	session := newGeminiSession()
	if strings.HasSuffix(path, ".json") {
		// Legacy whole-file record (pretty-printed, so not line-oriented).
		raw, err := io.ReadAll(io.LimitReader(file, geminiLegacyFileLimit))
		if err != nil {
			return convops.SessionEntry{}, false
		}
		session.applyRecord(raw)
	} else {
		reader := bufio.NewReaderSize(file, 64<<10)
		for {
			// Copilot's bounded line reader: an oversized line (a huge tool
			// result) is dropped rather than ending the scan, and a final
			// partially flushed line from a live writer is tolerated.
			line, readErr := readCopilotEventLine(reader)
			if len(line) > 0 {
				session.applyRecord(line)
			}
			if readErr != nil {
				if !errors.Is(readErr, io.EOF) {
					slog.Warn("gemini convstore: session scan stopped early; listing what was read",
						"path", path, "error", readErr)
				}
				break
			}
		}
	}

	if session.meta.SessionID == "" || session.meta.Kind == "subagent" {
		return convops.SessionEntry{}, false
	}
	resumable := false
	userMessages := 0
	firstPrompt := ""
	model := ""
	for _, msg := range session.messages {
		if msg.resumable {
			resumable = true
		}
		if msg.isUser {
			userMessages++
			if firstPrompt == "" && msg.resumable {
				firstPrompt = msg.userPrompt
			}
		}
		if msg.Model != "" {
			model = msg.Model
		}
	}
	if !resumable {
		return convops.SessionEntry{}, false
	}
	mtime := info.ModTime().UTC()
	modified := geminiTimestamp(session.meta.LastUpdated)
	if modified == "" {
		modified = mtime.Format(time.RFC3339)
	}
	created := geminiTimestamp(session.meta.StartTime)
	if created == "" {
		created = modified
	}
	return convops.SessionEntry{
		SessionID:    session.meta.SessionID,
		FullPath:     path,
		FileMtime:    mtime,
		FileSize:     info.Size(),
		FirstPrompt:  firstPrompt,
		Summary:      strings.TrimSpace(session.meta.Summary),
		MessageCount: userMessages,
		Created:      created,
		Modified:     modified,
		ProjectPath:  projectRoot,
		Harness:      GeminiName,
		Model:        model,
	}, true
}

// geminiLegacyFileLimit bounds a legacy whole-file `.json` read.
const geminiLegacyFileLimit = 64 << 20

// geminiIgnoredUserContent is sessionUtils.isIgnoredUserContent: slash
// commands, `?` help, and injected context blocks are not conversation turns.
func geminiIgnoredUserContent(trimmed string) bool {
	return trimmed == "" ||
		strings.HasPrefix(trimmed, "/") ||
		strings.HasPrefix(trimmed, "?") ||
		strings.HasPrefix(trimmed, "<session_context>") ||
		strings.HasPrefix(trimmed, "<hook_context>")
}

// geminiContentText flattens a PartListUnion (a string, a part object, or an
// array of strings/parts) to its text, ignoring non-text parts.
func geminiContentText(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	var text string
	if json.Unmarshal(raw, &text) == nil {
		return text
	}
	var part struct {
		Text string `json:"text"`
	}
	var parts []json.RawMessage
	if json.Unmarshal(raw, &parts) == nil {
		var b strings.Builder
		for _, p := range parts {
			if json.Unmarshal(p, &text) == nil {
				b.WriteString(text)
				continue
			}
			part.Text = ""
			if json.Unmarshal(p, &part) == nil {
				b.WriteString(part.Text)
			}
		}
		return b.String()
	}
	if json.Unmarshal(raw, &part) == nil {
		return part.Text
	}
	return ""
}

// geminiTimestamp normalizes Gemini's ISO-8601 stamps to RFC3339 UTC. An
// unparsable value passes through rather than being dropped.
func geminiTimestamp(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	parsed, err := time.Parse(time.RFC3339Nano, value)
	if err != nil {
		return value
	}
	return parsed.UTC().Format(time.RFC3339)
}

// syncGeminiConvIndex mirrors the listing into tclaude's conv_index cache and
// overlays the two tclaude-owned columns back onto it: the archived flag and
// the custom title (Gemini has no title store, so a tclaude rename lives only
// here). Upsert-only, for the reason Copilot's sync gives: GEMINI_CLI_HOME can
// be repointed, and evicting rows the current home does not mention would
// destroy tclaude state for conversations under another home.
func syncGeminiConvIndex(entries []convops.SessionEntry) {
	if len(entries) == 0 {
		return
	}
	cached := map[string]*db.ConvIndexRow{}
	if rows, err := db.ListAllConvIndex(); err != nil {
		slog.Warn("gemini convstore: conv_index unreadable; tclaude titles and archived state unavailable",
			"error", err)
	} else {
		for _, row := range rows {
			if row.Harness == GeminiName {
				cached[row.ConvID] = row
			}
		}
	}
	for i := range entries {
		row := cached[entries[i].SessionID]
		if row != nil {
			entries[i].CustomTitle = row.CustomTitle
			if !row.ArchivedAt.IsZero() {
				entries[i].ArchivedAt = row.ArchivedAt.UTC().Format(time.RFC3339)
			}
		}
		next := geminiEntryDBRow(entries[i])
		if row != nil {
			// Branches are observed by hooks, never by this cold read; keep
			// whatever a live observation recorded.
			next.GitBranch = row.GitBranch
			next.GitBranchStartup = row.GitBranchStartup
		}
		if err := db.UpsertConvIndex(next); err != nil {
			slog.Warn("gemini convstore: conv_index upsert failed; continuing from Gemini",
				"conv", entries[i].SessionID, "error", err)
		}
	}
}

// geminiEntryDBRow projects a listing entry onto the cache row. ArchivedAt is
// absent on purpose: SetConvIndexArchived owns that column.
func geminiEntryDBRow(entry convops.SessionEntry) *db.ConvIndexRow {
	return &db.ConvIndexRow{
		ConvID:       entry.SessionID,
		ProjectDir:   entry.ProjectPath,
		FullPath:     entry.FullPath,
		FileMtime:    entry.FileMtime,
		FileSize:     entry.FileSize,
		FirstPrompt:  entry.FirstPrompt,
		Summary:      entry.Summary,
		CustomTitle:  entry.CustomTitle,
		MessageCount: entry.MessageCount,
		Created:      entry.Created,
		Modified:     entry.Modified,
		ProjectPath:  entry.ProjectPath,
		IndexedAt:    time.Now(),
		Harness:      GeminiName,
	}
}

// Resolve maps a full id or an id prefix onto a conversation. Gemini session
// ids are UUIDs and unique across projects, so `global` only widens which
// conversations are considered.
func (s geminiConvStore) Resolve(idPrefix, cwd string, global bool) (*ConvRef, error) {
	if idPrefix == "" {
		return nil, nil
	}
	if global {
		cwd = ""
	}
	entries, err := s.ListConvs(cwd)
	if err != nil {
		return nil, fmt.Errorf("resolve Gemini conversation %q: %w", idPrefix, err)
	}
	for i := range entries {
		if entries[i].SessionID == idPrefix {
			return geminiConvRef(entries[i]), nil
		}
	}
	var match *convops.SessionEntry
	for i := range entries {
		if !strings.HasPrefix(entries[i].SessionID, idPrefix) {
			continue
		}
		if match != nil {
			return nil, fmt.Errorf("ambiguous conversation id %q: matches multiple Gemini conversations", idPrefix)
		}
		match = &entries[i]
	}
	if match == nil {
		return nil, nil
	}
	return geminiConvRef(*match), nil
}

func geminiConvRef(entry convops.SessionEntry) *ConvRef {
	return &ConvRef{ConvID: entry.SessionID, ProjectPath: entry.ProjectPath, Harness: GeminiName}
}

// find returns the listing entry for one conversation id.
func (s geminiConvStore) find(convID string) (convops.SessionEntry, bool, error) {
	entries, err := s.scan()
	if err != nil {
		return convops.SessionEntry{}, false, err
	}
	for _, entry := range entries {
		if entry.SessionID == convID {
			return entry, true, nil
		}
	}
	return convops.SessionEntry{}, false, nil
}

// Title returns the display title: a tclaude rename when one was made,
// otherwise Gemini's own summary, otherwise the first prompt. An unknown
// conversation is ("", nil).
func (s geminiConvStore) Title(convID string) (string, error) {
	if convID == "" {
		return "", nil
	}
	if row, err := db.GetConvIndex(convID); err == nil && row != nil &&
		row.Harness == GeminiName && row.CustomTitle != "" {
		return row.CustomTitle, nil
	}
	entry, ok, err := s.find(convID)
	if err != nil || !ok {
		return "", err
	}
	return entry.DisplayTitle(), nil
}

// SetTitle records a tclaude-side title for a Gemini conversation.
//
// Gemini CLI has no rename command and no title of its own — its `summary` is
// regenerated by the CLI — so there is nothing in Gemini's files tclaude may
// honestly write. The title lives in tclaude's conv_index overlay instead,
// which every tclaude surface reads; `gemini --list-sessions` keeps showing
// Gemini's own summary.
//
// The conversation is NOT required to exist in Gemini's store yet: a freshly
// launched pane has no resumable message until its first turn lands, and a
// spawn names its agent before that. A row written for an id Gemini never
// materializes is inert — no listing surfaces it.
func (geminiConvStore) SetTitle(convID, title string) error {
	if convID == "" {
		return fmt.Errorf("gemini SetTitle: empty conversation id")
	}
	if strings.TrimSpace(title) == "" {
		return fmt.Errorf("gemini SetTitle: refusing to write an empty title for %s", convID)
	}
	return db.SetConvIndexCustomTitle(convID, title, GeminiName)
}

// Exists reports whether the conversation is listable — the same predicate
// `gemini --resume <id>` applies — rather than whether some file mentions the
// id. cwd is ignored: ids are unique across projects.
func (s geminiConvStore) Exists(convID, _ string) (bool, error) {
	if convID == "" {
		return false, nil
	}
	_, ok, err := s.find(convID)
	return ok, err
}
