package db

import (
	"encoding/json"
	"github.com/stretchr/testify/require"
	"github.com/tofutools/tclaude/pkg/federation/proto"
	"testing"
	"time"
)

func TestFederationRotationAtomicAuthorityAndBackupTransfer(t *testing.T) {
	setupTestDB(t)
	old, _ := proto.NewIdentity()
	next, _ := proto.NewIdentity()
	require.NoError(t, TrustFederationPeer(FederationPeer{InstanceID: old.ID(), PubKey: old.Pub, Label: "mac", TrustLevel: FederationTrustUnrestricted}))
	pool, err := CreateFederationNodeGroup("workers")
	require.NoError(t, err)
	require.NoError(t, AddFederationNodeGroupPeer(pool.ID, old.ID()))
	require.NoError(t, UpsertFederationPeerGrant(FederationPeerGrant{Peer: old.ID(), Slug: "node.read"}))
	require.NoError(t, ReserveFederationTeleportLease(FederationTeleportLease{Direction: "out", Peer: old.ID(), Offer: "backup", SourceAgent: "source", State: "paused", Epoch: 3, Sequence: 7}, 2))
	require.NoError(t, IssueModelProxyLease(ModelProxyLease{ID: "paid", Peer: old.ID(), Request: "spawn", Kind: "spawn", Proxy: "payer", IdleSeconds: 86400}))
	d, err := Open()
	require.NoError(t, err)
	scope, _ := json.Marshal(map[string][]string{"peer": {old.ID() + "/team", "group:workers"}, "http_proxy": {"payer"}})
	_, err = d.Exec(`INSERT INTO agent_permissions(agent_id,slug,granted_at,scope_json) VALUES('actor','self.teleport',?,?)`, dbTime(time.Now()), string(scope))
	require.NoError(t, err)
	group, err := CreateAgentGroup("team", "")
	require.NoError(t, err)
	owner, _ := json.Marshal(map[string]any{"self.teleport": map[string][]string{"peer": {old.ID() + "/team"}}})
	_, err = d.Exec(`UPDATE agent_groups SET owner_scopes_json=? WHERE id=?`, string(owner), group)
	require.NoError(t, err)
	require.NoError(t, InsertFederationAgentMove(FederationAgentMove{Direction: "out", Peer: old.ID(), ID: "backup", SourceAgent: "source", State: "retired", Group: "team", MovedTo: &FederationMoveLink{Instance: old.ID(), Agent: "roaming", Offer: "backup"}}))
	_, err = d.Exec(`INSERT INTO federation_teleports(direction,peer,offer,chain,source_agent,created_at,state,snapshot) VALUES('out',?,'backup','chain','source',?,'confirmed',?)`, old.ID(), dbTime(time.Now()), `{"peer":"`+old.ID()+`","intent":{"origin_instance":"`+old.ID()+`"}}`)
	require.NoError(t, err)
	now := time.Now()
	r, err := proto.NewRotation(old, next, "", 1, now, 10*time.Minute)
	require.NoError(t, err)
	first, err := ObserveFederationRotation(r, now, 10*time.Minute)
	require.NoError(t, err)
	require.True(t, first)
	first, err = ObserveFederationRotation(r, now.Add(time.Minute), 0)
	require.NoError(t, err)
	require.False(t, first)
	require.Error(t, AcceptFederationRotation(old.ID(), now.Add(time.Minute)))
	require.NoError(t, AcceptFederationRotation(old.ID(), now.Add(11*time.Minute)))
	p, err := GetFederationPeer(next.ID())
	require.NoError(t, err)
	require.NotNil(t, p)
	require.Equal(t, "mac", p.Label)
	require.Equal(t, FederationTrustUnrestricted, p.TrustLevel)
	p, err = GetFederationPeer(old.ID())
	require.NoError(t, err)
	require.Nil(t, p)
	grants, err := ListFederationPeerGrants(next.ID())
	require.NoError(t, err)
	require.Len(t, grants, 1)
	peers, err := ListFederationNodeGroupPeers("workers")
	require.NoError(t, err)
	require.Equal(t, next.ID(), peers[0].InstanceID)
	backup, err := GetFederationTeleportLease("out", next.ID(), "backup")
	require.NoError(t, err)
	require.NotNil(t, backup)
	require.Equal(t, next.ID(), backup.Peer)
	require.EqualValues(t, 3, backup.Epoch)
	require.EqualValues(t, 7, backup.Sequence)
	paid, err := GetModelProxyLease("paid")
	require.NoError(t, err)
	require.True(t, paid.Revoked)
	require.Equal(t, old.ID(), paid.Peer, "billing provenance stays historical")
	var updated string
	require.NoError(t, d.QueryRow(`SELECT scope_json FROM agent_permissions WHERE agent_id='actor'`).Scan(&updated))
	require.Contains(t, updated, next.ID()+"/team")
	require.Contains(t, updated, "group:workers")
	require.NotContains(t, updated, old.ID())
	require.NoError(t, d.QueryRow(`SELECT owner_scopes_json FROM agent_groups WHERE id=?`, group).Scan(&updated))
	require.Contains(t, updated, next.ID()+"/team")
	move, err := GetFederationAgentMove("out", next.ID(), "backup")
	require.NoError(t, err)
	require.NotNil(t, move)
	require.Equal(t, next.ID(), move.Peer)
	require.Equal(t, next.ID(), move.MovedTo.Instance, "live bounce address follows its peer")
	require.NoError(t, d.QueryRow(`SELECT snapshot FROM federation_teleports WHERE peer=?`, next.ID()).Scan(&updated))
	require.Contains(t, updated, `"origin_instance":"`+old.ID()+`"`)
	require.Error(t, TrustFederationPeer(FederationPeer{InstanceID: old.ID(), PubKey: old.Pub}), "retired key must not regain authority through ordinary trust")
	require.NoError(t, AcceptFederationRotation(old.ID(), now.Add(time.Hour)), "accepted retry is idempotent")
}

func TestFederationRotationConflictingSuccessorsFailClosed(t *testing.T) {
	setupTestDB(t)
	old, _ := proto.NewIdentity()
	a, _ := proto.NewIdentity()
	b, _ := proto.NewIdentity()
	require.NoError(t, TrustFederationPeer(FederationPeer{InstanceID: old.ID(), PubKey: old.Pub}))
	now := time.Now()
	ra, err := proto.NewRotation(old, a, "", 1, now, time.Minute)
	require.NoError(t, err)
	rb, err := proto.NewRotation(old, b, "", 1, now, time.Minute)
	require.NoError(t, err)
	_, err = ObserveFederationRotation(ra, now, time.Minute)
	require.NoError(t, err)
	_, err = ObserveFederationRotation(rb, now, time.Minute)
	require.NoError(t, err)
	require.Error(t, AcceptFederationRotation(old.ID(), now.Add(time.Hour)))
	rows, err := ListFederationIdentityRotations()
	require.NoError(t, err)
	require.Equal(t, "conflict", rows[0].State)
	p, err := GetFederationPeer(old.ID())
	require.NoError(t, err)
	require.NotNil(t, p)
	require.NoError(t, RebindFederationIdentity(old.ID(), b.ID(), b.Pub, now.Add(time.Hour)))
	p, err = GetFederationPeer(b.ID())
	require.NoError(t, err)
	require.NotNil(t, p)
}

func TestFederationIdentityLocalHistoryBeyondPublicProofBudget(t *testing.T) {
	setupTestDB(t)
	first, err := proto.NewIdentity()
	require.NoError(t, err)
	require.NoError(t, TrustFederationPeer(FederationPeer{InstanceID: first.ID(), PubKey: first.Pub, Label: "recovering"}))
	current := first
	for range 6 {
		next, err := proto.NewIdentity()
		require.NoError(t, err)
		require.NoError(t, RebindFederationIdentity(current.ID(), next.ID(), next.Pub, time.Now()))
		current = next
	}
	resolved, err := ResolveFederationIdentitySuccessor(first.ID())
	require.NoError(t, err)
	require.Equal(t, current.ID(), resolved)
	d, err := Open()
	require.NoError(t, err)
	_, err = d.Exec(`UPDATE federation_identity_rotations SET new_instance=? WHERE old_instance=?`, first.ID(), first.ID())
	require.NoError(t, err)
	_, err = ResolveFederationIdentitySuccessor(first.ID())
	require.Error(t, err, "corrupt cycles must fail closed")
}
