package agentd

import "net/http"

func registerDashboardFederationRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /api/federation/hub/boards", dashboardFederationRoute(hubOperatorRoute("boards.list")))
	mux.HandleFunc("PATCH /api/federation/hub/boards/{board}", dashboardFederationRoute(hubOperatorRoute("boards.patch")))
	mux.HandleFunc("DELETE /api/federation/hub/boards/{board}", dashboardFederationRoute(hubOperatorRoute("boards.delete")))
	registerBoardRoutes(mux, "/api/federation/boards", true)
	mux.HandleFunc("GET /api/federation/hub/run", dashboardFederationRoute(hubOperatorRoute("run.status")))
	mux.HandleFunc("POST /api/federation/hub/run", dashboardFederationRoute(hubOperatorRoute("run.start")))
	mux.HandleFunc("GET /api/federation/hub/run/jobs/{job_id}", dashboardFederationRoute(hubOperatorRoute("run.job")))
	mux.HandleFunc("GET /api/federation/hub/run/jobs/{job_id}/logs", dashboardFederationRoute(hubOperatorRoute("run.logs")))
	mux.HandleFunc("GET /api/federation/hub/audit", dashboardFederationRoute(hubOperatorRoute("audit")))
	mux.HandleFunc("GET /api/federation/hub/update", dashboardFederationRoute(hubOperatorRoute("update.status")))
	mux.HandleFunc("POST /api/federation/hub/update", dashboardFederationRoute(hubOperatorRoute("update.start")))
	mux.HandleFunc("GET /api/federation/hub/update/jobs/{job_id}", dashboardFederationRoute(hubOperatorRoute("update.job")))
	mux.HandleFunc("GET /api/federation/hub/status", dashboardFederationRoute(hubOperatorRoute("status")))
	mux.HandleFunc("POST /api/federation/hub/claim", dashboardFederationRoute(hubOperatorRoute("claim")))
	mux.HandleFunc("GET /api/federation/hub/admins", dashboardFederationRoute(hubOperatorRoute("admins.list")))
	mux.HandleFunc("POST /api/federation/hub/admins", dashboardFederationRoute(hubOperatorRoute("admins.add")))
	mux.HandleFunc("DELETE /api/federation/hub/admins/{instance}", dashboardFederationRoute(hubOperatorRoute("admins.remove")))
	mux.HandleFunc("GET /api/federation/hub/admissions", dashboardFederationRoute(hubOperatorRoute("admissions.list")))
	mux.HandleFunc("POST /api/federation/hub/admissions", dashboardFederationRoute(hubOperatorRoute("admissions.admit")))
	mux.HandleFunc("DELETE /api/federation/hub/admissions/{instance}", dashboardFederationRoute(hubOperatorRoute("admissions.revoke")))
	mux.HandleFunc("GET /api/federation/hub/invites", dashboardFederationRoute(hubOperatorRoute("invites.list")))
	mux.HandleFunc("POST /api/federation/hub/invites", dashboardFederationRoute(hubOperatorRoute("invites.create")))
	mux.HandleFunc("DELETE /api/federation/hub/invites/{token_hash}", dashboardFederationRoute(hubOperatorRoute("invites.revoke")))
	mux.HandleFunc("GET /api/federation/hub/spaces", dashboardFederationRoute(hubOperatorRoute("spaces.list")))
	mux.HandleFunc("PUT /api/federation/hub/spaces", dashboardFederationRoute(hubOperatorRoute("spaces.set")))
	mux.HandleFunc("GET /api/federation/hub/settings", dashboardFederationRoute(hubOperatorRoute("settings.get")))
	mux.HandleFunc("PATCH /api/federation/hub/settings", dashboardFederationRoute(hubOperatorRoute("settings.patch")))
	mux.HandleFunc("POST /api/federation/hub/identity/recover", dashboardFederationRoute(hubOperatorRoute("identity.recover")))
	mux.HandleFunc("POST /api/federation/hub/identity/revoke-old", dashboardFederationRoute(hubOperatorRoute("identity.revoke-old")))
	mux.HandleFunc("GET /api/federation/hub/health", dashboardFederationRoute(hubOperatorRoute("health")))
	mux.HandleFunc("GET /api/federation/hub/logs", dashboardFederationRoute(hubOperatorRoute("logs")))
	mux.HandleFunc("GET /api/federation/terminal-file", dashboardFederationRoute(handleDashboardFederationTerminalFile))
	mux.HandleFunc("POST /api/federation/terminal-attachments", dashboardFederationRoute(handleDashboardFederationTerminalAttachments))
	mux.HandleFunc("GET /api/federation/terminal", dashboardFederationRoute(handleDashboardFederationTerminal))
	mux.HandleFunc("GET /api/federation/sessions", dashboardFederationRoute(handleFederationSessions))
	mux.HandleFunc("POST /api/federation/offer-config", dashboardFederationRoute(handleFederationOfferConfig))
	mux.HandleFunc("POST /api/federation/share-agent", dashboardFederationRoute(handleFederationShareAgent))
	mux.HandleFunc("POST /api/federation/move-agent", dashboardFederationRoute(handleFederationShareAgent))
	mux.HandleFunc("GET /api/federation/bundle-offers", dashboardFederationRoute(handleFederationBundleOffers))
	mux.HandleFunc("GET /api/federation/bundle-offers/{id}/contents", dashboardFederationRoute(handleFederationBundleContents))
	mux.HandleFunc("GET /api/federation/bundle-offers/{id}/download", dashboardFederationRoute(handleFederationBundleDownload))
	mux.HandleFunc("POST /api/federation/bundle-offers/{id}/fetch", dashboardFederationRoute(handleFederationBundleFetch))
	mux.HandleFunc("POST /api/federation/bundle-offers/{id}/import", dashboardFederationRoute(handleFederationBundleImport))
	mux.HandleFunc("POST /api/federation/bundle-offers/{id}/decline", dashboardFederationRoute(handleFederationBundleDecline))
	mux.HandleFunc("POST /api/federation/profiles/{name}/offer", dashboardFederationRoute(handleFederationNodeProfileOffer))
	mux.HandleFunc("GET /api/federation/node-labels", dashboardFederationRoute(handleFederationNodeLabels))
	mux.HandleFunc("POST /api/federation/node-labels", dashboardFederationRoute(handleFederationNodeLabels))
	mux.HandleFunc("GET /api/federation/nodes/health", dashboardFederationRoute(handleFleetHealthConfig))
	mux.HandleFunc("POST /api/federation/nodes/health", dashboardFederationRoute(handleFleetHealthConfig))
	mux.HandleFunc("POST /api/federation/jobs", dashboardFederationRoute(handleFederationJobSend))
	mux.HandleFunc("GET /api/federation/jobs", dashboardFederationRoute(handleFederationJobs))
	mux.HandleFunc("GET /api/federation/jobs/{id}", dashboardFederationRoute(handleFederationJobs))
	mux.HandleFunc("GET /api/federation/jobs/{id}/output", dashboardFederationRoute(handleFederationJobOutput))
	mux.HandleFunc("GET /api/federation/identity/rotations", dashboardFederationRoute(handleFederationIdentityRotations))
	mux.HandleFunc("POST /api/federation/identity/rotate", dashboardFederationRoute(handleFederationIdentityRotate))
	mux.HandleFunc("GET /api/federation/jobs/{id}/follow", dashboardFederationRoute(handleFederationJobFollow))
	mux.HandleFunc("GET /api/federation/jobs/{id}/logs", dashboardFederationRoute(handleFederationJobLogs))
	mux.HandleFunc("POST /api/federation/jobs/{id}/cancel", dashboardFederationRoute(handleFederationJobCancel))
	mux.HandleFunc("POST /api/federation/jobs/{id}/approve", dashboardFederationRoute(handleFederationJobApprove))
	mux.HandleFunc("POST /api/federation/jobs/{id}/retry", dashboardFederationRoute(handleFederationJobRetry))
	mux.HandleFunc("POST /api/federation/jobs/{id}/acknowledge-stopped", dashboardFederationRoute(handleFederationJobAcknowledgeStopped))
	mux.HandleFunc("GET /api/federation/repos", dashboardFederationRoute(handleFederationRepos))
	mux.HandleFunc("POST /api/federation/repos", dashboardFederationRoute(handleFederationRepos))
	mux.HandleFunc("PUT /api/federation/repos/{name}", dashboardFederationRoute(handleFederationRepos))
	mux.HandleFunc("DELETE /api/federation/repos/{name}", dashboardFederationRoute(handleFederationRepos))
	mux.HandleFunc("GET /api/federation/viewers", dashboardFederationRoute(handleFederationViewers))
	mux.HandleFunc("POST /api/federation/viewers/{id}/kick", dashboardFederationRoute(handleFederationKick))
	mux.HandleFunc("GET /api/federation/models/control", dashboardFederationRoute(handleModelProxyControl))
	mux.HandleFunc("POST /api/federation/models/control", dashboardFederationRoute(handleModelProxyControl))
	mux.HandleFunc("GET /api/federation/models/leases", dashboardFederationRoute(handleModelProxyLeases))
	mux.HandleFunc("POST /api/federation/models/leases", dashboardFederationRoute(handleModelProxyLeases))
	mux.HandleFunc("GET /api/federation/models/usage", dashboardFederationRoute(handleModelProxyUsage))
	mux.HandleFunc("GET /api/federation/spawn-requests", dashboardFederationRoute(handleFederationSpawnRequestList))
	mux.HandleFunc("POST /api/federation/spawn-requests", dashboardFederationRoute(handleFederationSpawnRequestSend))
	mux.HandleFunc("POST /api/federation/spawn-requests/{id}/approve", dashboardFederationRoute(handleFederationSpawnRequestApprove))
	mux.HandleFunc("POST /api/federation/spawn-requests/{id}/deny", dashboardFederationRoute(handleFederationSpawnRequestDeny))
	mux.HandleFunc("POST /api/federation/spawn-requests/{id}/abandon", dashboardFederationRoute(handleFederationSpawnRequestAbandon))
	mux.HandleFunc("GET /api/federation/outbox", dashboardFederationRoute(handleFederationOutbox))
	mux.HandleFunc("POST /api/federation/send", dashboardFederationRoute(handleFederationSend))
	mux.HandleFunc("POST /api/federation/notify", dashboardFederationRoute(handleFederationNotify))
	mux.HandleFunc("GET /api/federation/inbox", dashboardFederationRoute(handleFederationInbox))
	mux.HandleFunc("GET /api/federation/away", dashboardFederationRoute(handleFederationAway))
	mux.HandleFunc("POST /api/federation/away", dashboardFederationRoute(handleFederationAway))
	mux.HandleFunc("POST /api/federation/return", dashboardFederationRoute(handleFederationReturn))
	mux.HandleFunc("POST /api/federation/answer", dashboardFederationRoute(handleFederationAwayAnswer))
	mux.HandleFunc("GET /api/federation/moves", dashboardFederationRoute(handleFederationMoves))
	mux.HandleFunc("GET /api/federation/moves/{id}", dashboardFederationRoute(handleFederationMoves))
	mux.HandleFunc("POST /api/federation/moves/{id}/abandon", dashboardFederationRoute(handleFederationMoveAbandon))
	mux.HandleFunc("GET /api/federation/teleport", dashboardFederationRoute(handleFederationTeleportSwitch))
	mux.HandleFunc("PUT /api/federation/teleport", dashboardFederationRoute(handleFederationTeleportSwitch))
	mux.HandleFunc("GET /api/federation/access-requests", dashboardFederationRoute(handleFederationAccessRequests))
	mux.HandleFunc("POST /api/federation/access-requests/{id}/decision", dashboardFederationRoute(handleFederationAccessRequests))
	mux.HandleFunc("GET /api/federation/status", dashboardFederationRoute(handleFederationStatus))
	mux.HandleFunc("GET /api/federation/links", dashboardFederationRoute(handleFederationLinks))
	mux.HandleFunc("GET /api/federation/audit", dashboardFederationRoute(handleFederationAudit))
	mux.HandleFunc("POST /api/federation/config", dashboardFederationRoute(handleFederationConfig))
	mux.HandleFunc("GET /api/federation/enroll-tokens", dashboardFederationRoute(handleFederationEnrollmentTokens))
	mux.HandleFunc("POST /api/federation/enroll-tokens", dashboardFederationRoute(handleFederationEnrollmentTokens))
	mux.HandleFunc("POST /api/federation/enroll-tokens/{id}/revoke", dashboardFederationRoute(handleFederationEnrollmentTokens))
	mux.HandleFunc("GET /api/federation/enrollments", dashboardFederationRoute(handleFederationEnrollments))
	mux.HandleFunc("POST /api/federation/enroll/preview", dashboardFederationRoute(handleFederationEnroll))
	mux.HandleFunc("POST /api/federation/enroll", dashboardFederationRoute(handleFederationEnroll))
	mux.HandleFunc("POST /api/federation/peers/trust", dashboardFederationRoute(handleFederationTrust))
	mux.HandleFunc("POST /api/federation/peers/untrust", dashboardFederationRoute(handleFederationUntrust))
	mux.HandleFunc("GET /api/federation/grants", dashboardFederationRoute(handleFederationPeerGrants))
	mux.HandleFunc("POST /api/federation/grants", dashboardFederationRoute(handleFederationPeerGrants))
	mux.HandleFunc("DELETE /api/federation/grants", dashboardFederationRoute(handleFederationPeerGrants))
	mux.HandleFunc("GET /api/federation/profiles", dashboardFederationRoute(handleFederationNodeProfiles))
	mux.HandleFunc("POST /api/federation/profiles", dashboardFederationRoute(handleFederationNodeProfiles))
	mux.HandleFunc("GET /api/federation/profiles/{name}", dashboardFederationRoute(handleFederationNodeProfiles))
	mux.HandleFunc("PUT /api/federation/profiles/{name}", dashboardFederationRoute(handleFederationNodeProfiles))
	mux.HandleFunc("DELETE /api/federation/profiles/{name}", dashboardFederationRoute(handleFederationNodeProfiles))
	mux.HandleFunc("POST /api/federation/profiles/{name}/apply", dashboardFederationRoute(handleFederationNodeProfileApply))
	mux.HandleFunc("PUT /api/federation/default-peer-profile", dashboardFederationRoute(handleFederationDefaultPeerProfile))
	mux.HandleFunc("GET /api/federation/nodes/groups", dashboardFederationRoute(handleFederationNodeGroups))
	mux.HandleFunc("POST /api/federation/nodes/groups", dashboardFederationRoute(handleFederationNodeGroups))
	mux.HandleFunc("DELETE /api/federation/nodes/groups/{name}", dashboardFederationRoute(handleFederationNodeGroups))
	mux.HandleFunc("POST /api/federation/nodes/groups/{name}/members", dashboardFederationRoute(handleFederationNodeGroupMembers))
	mux.HandleFunc("DELETE /api/federation/nodes/groups/{name}/members", dashboardFederationRoute(handleFederationNodeGroupMembers))
}

// Federation administration belongs to the cookie-authenticated local human.
// PeerViewHandler classifies these routes as local-only and never calls this.
func dashboardFederationRoute(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !checkDashboardAuth(w, r) {
			return
		}
		w.Header().Set("Cache-Control", "private, no-store")
		next(w, asDashboardHumanPeer(r))
	}
}
