package agentd

// Dashboard routes deliberately left local-only. The route guard test requires
// an explicit decision here whenever a dashboard route is added.
var peerViewLocalRoutes = []string{
	"/",
	"/api/agent-generations/",
	"/api/agent-windows",
	"/api/agents/",
	"/api/audit",
	"/api/auth/session",
	"/api/browse-directories",
	"/api/browser-notifications",
	"/api/claude-settings/default-model",
	"/api/cleanup/",
	"GET /api/node/update",
	"GET /api/node/run",
	"POST /api/node/run",
	"GET /api/node/run/jobs/{id}",
	"GET /api/node/run/jobs/{id}/logs",
	"GET /api/node/run/settings",
	"PUT /api/node/run/settings",
	"POST /api/node/update",
	"GET /api/node/update/jobs/{id}",
	"GET /api/harnesses/availability",
	"GET /api/harnesses/operations",
	"POST /api/harnesses/operations",
	"POST /api/harnesses/credentials",
	"GET /api/harnesses/credentials/backups",
	"POST /api/harnesses/credentials/push",
	"POST /api/harnesses/credentials/backup",
	"POST /api/harnesses/credentials/restore",
	"GET /api/harnesses/operations/jobs/{id}",
	"/api/config",
	"/api/conversations",
	"/api/cost-factor",
	"/api/costs",
	"/api/create-directory",
	"/api/cron",
	"/api/cron/",
	"/api/dashboard/prefs",
	"/api/delete-directory",
	"/api/export-jobs/",
	"GET /api/federation/models/control",
	"POST /api/federation/models/control",
	"GET /api/federation/models/leases",
	"POST /api/federation/models/leases",
	"GET /api/federation/models/usage",
	"GET /api/federation/moves",
	"GET /api/federation/moves/{id}",
	"POST /api/federation/moves/{id}/abandon",
	"GET /api/federation/teleport",
	"PUT /api/federation/teleport",
	"GET /api/federation/status",
	"GET /api/federation/access-requests",
	"POST /api/federation/access-requests/{id}/decision",
	"GET /api/federation/links",
	"GET /api/federation/audit",
	"POST /api/federation/config",
	"GET /api/federation/enroll-tokens",
	"POST /api/federation/enroll-tokens",
	"POST /api/federation/enroll-tokens/{id}/revoke",
	"GET /api/federation/enrollments",
	"POST /api/federation/enroll/preview",
	"POST /api/federation/enroll",
	"POST /api/federation/peers/trust",
	"POST /api/federation/peers/untrust",
	"GET /api/federation/grants",
	"POST /api/federation/grants",
	"DELETE /api/federation/grants",
	"GET /api/federation/profiles",
	"POST /api/federation/profiles",
	"GET /api/federation/profiles/{name}",
	"PUT /api/federation/profiles/{name}",
	"DELETE /api/federation/profiles/{name}",
	"POST /api/federation/profiles/{name}/apply",
	"PUT /api/federation/default-peer-profile",
	"GET /api/federation/nodes/groups",
	"POST /api/federation/nodes/groups",
	"DELETE /api/federation/nodes/groups/{name}",
	"POST /api/federation/nodes/groups/{name}/members",
	"DELETE /api/federation/nodes/groups/{name}/members",
	"/api/git-repositories",
	"/api/git-repositories/batch",
	"/api/group-term-ws/",
	"/api/groups/{group}/sandbox-profile",
	"/api/groups/{name}/attachment",
	"/api/groups/{name}/spawn-harness-policy",
	"/api/hide/",
	"/api/human-messages/",
	"/api/human-messages/clear",
	"/api/human-messages/delete",
	"/api/human-messages/read",
	"/api/human-messages/reply",
	"/api/instance",
	"/api/jobs",
	"/api/jump/",
	"/api/logs",
	"/api/mailbox",
	"/api/mailboxes",
	"/api/notifications",
	"/api/open-window-ws/",
	"/api/open-window/",
	"/api/pending/delete/",
	"/api/pending/focus/",
	"GET /api/peer/{node}/{tail...}",
	"POST /api/peer/{node}/{tail...}",
	"/api/perf",
	"/api/perf/reset",
	"/api/permissions",
	"/api/pick-directory",
	"/api/power-on",
	"/api/pr-checks",
	"/api/rename-directory",
	"/api/replaced",
	"/api/retired",
	"/api/roles",
	"/api/roles/{name}",
	"/api/sandbox-profile-default",
	"/api/sandbox-profile-drafts/{token}",
	"/api/sandbox-profile-read-exclusions",
	"/api/sandbox-profiles",
	"/api/sandbox-profiles/{name}",
	"/api/scribe",
	"/api/shutdown",
	"/api/slop/channel",
	"/api/slop/nowplaying",
	"/api/slop/volumes",
	"/api/snapshot",
	"/api/spawn-attachments",
	"/api/spawn-focus-ws/",
	"/api/spawn-harness-policy",
	"/api/spawn-profile-default",
	"/api/spawn-profiles",
	"/api/spawn-profiles/{name}",
	"/api/spawn-timing",
	"/api/spawn/effective-sandbox",
	"/api/standing-order-hooks",
	"/api/standing-orders",
	"/api/standing-orders/",
	"/api/sudo",
	"/api/sudo/",
	"/api/templates",
	"/api/templates/{name}",
	"/api/term-ws/",
	"/api/term/",
	"/api/terminal-attachments",
	"/api/terminal-file",
	"/api/triggers",
	"/api/triggers/",
	"/api/tui/",
	"/api/tui/attach-ws/",
	"/api/usage-history",
	"/api/usage-history/point",
	"/api/worktrees",
	"/api/worktrees/cleanup",
	"/api/worktrees/progress",
	"/dashboard/login",
	"/static/",
	"/terminals",
	"/terminals/",
	"DELETE /api/groups/{name}",
	"DELETE /api/groups/{name}/links/{id}",
	"DELETE /api/groups/{name}/members/{conv}",
	"DELETE /api/groups/{name}/owners/{conv}",
	"DELETE /api/groups/{name}/standing-orders/{id}",
	"DELETE /v1/process/templates/{id}",
	"GET /api/groups/{name}/export",
	"GET /api/groups/{name}/process",
	"GET /api/groups/{name}/standing-orders",
	"GET /api/groups/{name}/worktrees",
	"GET /api/sandbox-profiles/export",
	"GET /api/spawn-launch-defaults",
	"GET /api/spawn-profiles/export",
	"GET /api/starters",
	"GET /api/starters/{name}",
	"GET /api/templates/{name}/export",
	"GET /v1/process/template-heads",
	"GET /v1/process/templates",
	"GET /v1/process/templates/{id}",
	"PATCH /api/groups/{name}",
	"PATCH /api/groups/{name}/links/{id}",
	"PATCH /api/groups/{name}/members/{conv}",
	"POST /api/access-requests/{id}/decision",
	"POST /api/groups",
	"POST /api/groups/import",
	"POST /api/groups/import/inspect",
	"POST /api/groups/{name}/clone",
	"POST /api/groups/{name}/links",
	"POST /api/groups/{name}/members",
	"POST /api/groups/{name}/owners",
	"POST /api/groups/{name}/process/advance",
	"POST /api/groups/{name}/rebrief",
	"POST /api/groups/{name}/rename",
	"POST /api/groups/{name}/retire",
	"POST /api/groups/{name}/spawn",
	"POST /api/groups/{name}/stand-down",
	"POST /api/groups/{name}/standing-orders/{id}",
	"POST /api/mailbox/delete",
	"POST /api/mailbox/mark-read",
	"POST /api/mailbox/wipe",
	"POST /api/message",
	"POST /api/operator-message",
	"POST /api/sandbox-profile-directories/{action}",
	"POST /api/sandbox-profile-enforcement",
	"POST /api/sandbox-profiles/import",
	"POST /api/sandbox-profiles/import/inspect",
	"POST /api/spawn-profiles/from-agent",
	"POST /api/spawn-profiles/import",
	"POST /api/spawn-profiles/import/inspect",
	"POST /api/starters/{name}/install",
	"POST /api/templates/from-group",
	"POST /api/templates/import",
	"POST /api/templates/{name}/deploy",
	"POST /api/templates/{name}/instantiate",
	"POST /api/templates/{name}/reinforce",
	"POST /v1/process/templates",
	"POST /v1/process/templates/{id}",
	"POST /v1/process/validate",
	"PUT /api/groups/{name}/parent",
}
