package processcmd

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/GiGurra/boa/pkg/boa"
	"github.com/spf13/cobra"
	"github.com/tofutools/tclaude/pkg/claude/agent"
	"github.com/tofutools/tclaude/pkg/claude/process/engine"
	"github.com/tofutools/tclaude/pkg/common"
)

const (
	processEventPageMax                = 16
	maxProcessEventPayloadDisplayBytes = 512
)

var errProcessDaemonAlreadyReported = errors.New("daemon requirement already reported")

type processRunJSON struct {
	ID                    string            `json:"id"`
	TemplateRef           string            `json:"templateRef"`
	Params                map[string]string `json:"params"`
	ProgramAuthorizations []string          `json:"programAuthorizations"`
	Status                engine.RunStatus  `json:"status"`
	StateVersion          int64             `json:"stateVersion"`
	Checkpoint            engine.Checkpoint `json:"checkpoint"`
	Action                string            `json:"action"`
	NeedsReconcile        bool              `json:"needsReconcile"`
	CreatedAt             time.Time         `json:"createdAt"`
	UpdatedAt             time.Time         `json:"updatedAt"`
}

type processRunSummaryJSON struct {
	ID           string           `json:"id"`
	TemplateRef  string           `json:"templateRef"`
	Status       engine.RunStatus `json:"status"`
	StateVersion int64            `json:"stateVersion"`
	CreatedAt    time.Time        `json:"createdAt"`
	UpdatedAt    time.Time        `json:"updatedAt"`
}

type processRunEventJSON struct {
	Sequence   int64           `json:"sequence"`
	OccurredAt time.Time       `json:"occurredAt"`
	NodeID     string          `json:"nodeId"`
	Kind       string          `json:"kind"`
	Payload    json.RawMessage `json:"payload"`
	Actor      string          `json:"actor"`
}

type processRunParams struct {
	TemplateID string   `pos:"true" help:"Saved process-template id to instantiate"`
	RunID      string   `long:"run-id" optional:"true" help:"Explicit run id (normally generated by agentd)"`
	Params     []string `long:"param" optional:"true"`
	Authorize  []string `long:"authorize-program-profile" optional:"true"`
	AskHuman   string   `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func processRunCmd() *cobra.Command {
	return boa.CmdT[processRunParams]{
		Use:         "run",
		Short:       "Instantiate and run the saved template head through agentd",
		Long:        "Pins the exact saved template head and initial checkpoint transactionally. Repeat --param key=value and --authorize-program-profile profile for every exact program profile the run may execute. Use --authorize-program-profile= to explicitly authorize an empty profile.",
		ParamEnrich: common.DefaultParamEnricher(),
		InitFuncCtx: func(ctx *boa.HookContext, p *processRunParams, cmd *cobra.Command) error {
			boa.GetParamT(ctx, &p.Params).SetNoFlag(true)
			cmd.Flags().StringArrayVar(&p.Params, "param", nil, "Template parameter key=value. Repeatable; values may contain commas or '='.")
			boa.GetParamT(ctx, &p.Authorize).SetNoFlag(true)
			cmd.Flags().StringArrayVar(&p.Authorize, "authorize-program-profile", nil, "Explicitly authorize one exact program profile for this run. Repeatable.")
			return nil
		},
		RunFunc: func(p *processRunParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessRun(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessRun(p *processRunParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	params, err := parseProcessParams(p.Params)
	if err != nil {
		return err
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	request := struct {
		ID                       string            `json:"id,omitempty"`
		TemplateID               string            `json:"templateId"`
		Params                   map[string]string `json:"params"`
		AuthorizeProgramProfiles []string          `json:"authorizeProgramProfiles"`
	}{
		ID: strings.TrimSpace(p.RunID), TemplateID: strings.TrimSpace(p.TemplateID),
		Params: params, AuthorizeProgramProfiles: append([]string(nil), p.Authorize...),
	}
	if request.TemplateID == "" {
		return fmt.Errorf("template id is required")
	}
	var run processRunJSON
	if err := agent.DaemonRequest(http.MethodPost, "/v1/process/runs", request, &run,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Created process run %s\n", run.ID)
	printProcessRun(stdout, &run)
	fmt.Fprintf(stdout, "Next: tclaude process show %s; tclaude process events %s\n", run.ID, run.ID)
	return nil
}

type processRunsLsParams struct {
	After string `long:"after" optional:"true" help:"Exclusive run-id cursor"`
	Limit int    `long:"limit" optional:"true" help:"Maximum rows (1..32)"`
}

func processRunsLsCmd() *cobra.Command {
	return boa.CmdT[processRunsLsParams]{
		Use:         "ls",
		Short:       "List daemon-owned process runs",
		ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processRunsLsParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessRunsLs(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessRunsLs(p *processRunsLsParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	query := url.Values{}
	if after := strings.TrimSpace(p.After); after != "" {
		query.Set("after", after)
	}
	if p.Limit != 0 {
		if p.Limit < 1 || p.Limit > 32 {
			return fmt.Errorf("--limit must be 1..32")
		}
		query.Set("limit", strconv.Itoa(p.Limit))
	}
	path := "/v1/process/runs"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var response struct {
		Runs []processRunSummaryJSON `json:"runs"`
		Next string                  `json:"next"`
	}
	if err := agent.DaemonRequest(http.MethodGet, path, nil, &response, agent.DaemonOpts{RetryOutput: stderr}); err != nil {
		return err
	}
	if len(response.Runs) == 0 {
		fmt.Fprintln(stdout, "No process runs.")
		return nil
	}
	tw := newTable(stdout)
	fmt.Fprintln(tw, "ID\tTEMPLATE\tSTATUS\tUPDATED")
	for _, run := range response.Runs {
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\n", run.ID, run.TemplateRef, run.Status, formatTime(run.UpdatedAt))
	}
	if err := tw.Flush(); err != nil {
		return err
	}
	if response.Next != "" {
		fmt.Fprintf(stdout, "next=%s\n", response.Next)
	}
	return nil
}

type processRunIDParams struct {
	RunID string `pos:"true" help:"Process run id"`
}

func processShowCmd() *cobra.Command {
	return processRunReadCmd("show", "Show one daemon-owned process run", false)
}

type processEventsParams struct {
	RunID string `pos:"true" help:"Process run id"`
	After int64  `long:"after" optional:"true" help:"Exclusive event-sequence cursor"`
	Limit int    `long:"limit" optional:"true" default:"16" help:"Maximum rows (1..16)"`
}

func processEventsCmd() *cobra.Command {
	return boa.CmdT[processEventsParams]{
		Use:         "events",
		Short:       "Show ordered human-facing evidence for one process run",
		ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processEventsParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessEvents(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessEvents(p *processEventsParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	runID := strings.TrimSpace(p.RunID)
	if runID == "" {
		return fmt.Errorf("run id is required")
	}
	if p.After < 0 {
		return fmt.Errorf("--after must be a non-negative sequence")
	}
	if p.Limit < 1 || p.Limit > processEventPageMax {
		return fmt.Errorf("--limit must be 1..%d", processEventPageMax)
	}
	query := url.Values{}
	if p.After != 0 {
		query.Set("after", strconv.FormatInt(p.After, 10))
	}
	query.Set("limit", strconv.Itoa(p.Limit))
	path := "/v1/process/runs/" + url.PathEscape(runID) + "/events"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var response struct {
		Events []processRunEventJSON `json:"events"`
		Next   int64                 `json:"next"`
	}
	if err := agent.DaemonRequest(http.MethodGet, path, nil, &response,
		agent.DaemonOpts{RetryOutput: stderr}); err != nil {
		return err
	}
	if len(response.Events) == 0 {
		if p.After == 0 {
			fmt.Fprintf(stdout, "No evidence recorded for process run %s.\n", runID)
		} else {
			fmt.Fprintf(stdout, "No evidence after sequence %d for process run %s.\n", p.After, runID)
		}
		return nil
	}
	tw := newTable(stdout)
	fmt.Fprintln(tw, "SEQ\tTIME\tNODE\tKIND\tACTOR\tPAYLOAD")
	for _, event := range response.Events {
		fmt.Fprintf(tw, "%d\t%s\t%s\t%s\t%s\t%s\n",
			event.Sequence, formatTime(event.OccurredAt), displayProcessEventField(event.NodeID),
			event.Kind, displayProcessEventField(event.Actor), formatProcessEventPayload(event.Payload))
	}
	if err := tw.Flush(); err != nil {
		return err
	}
	if response.Next != 0 {
		fmt.Fprintf(stdout, "next=%d\n", response.Next)
	}
	return nil
}

func displayProcessEventField(value string) string {
	if value == "" {
		return "-"
	}
	return value
}

func formatProcessEventPayload(payload json.RawMessage) string {
	var compact bytes.Buffer
	if err := json.Compact(&compact, payload); err != nil {
		return "<invalid JSON>"
	}
	value := compact.String()
	if len(value) <= maxProcessEventPayloadDisplayBytes {
		return value
	}
	cut := maxProcessEventPayloadDisplayBytes - len("...")
	for cut > 0 && !utf8.ValidString(value[:cut]) {
		cut--
	}
	return value[:cut] + "..."
}

func processReconcileCmd() *cobra.Command {
	return processRunReadCmd("reconcile", "Inspect whether a run needs explicit reconciliation", true)
}

func processRunReadCmd(use, short string, reconcileOnly bool) *cobra.Command {
	return boa.CmdT[processRunIDParams]{
		Use: use, Short: short, ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processRunIDParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessShow(p, reconcileOnly, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessShow(p *processRunIDParams, reconcileOnly bool, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	run, err := fetchProcessRun(p.RunID, stderr)
	if err != nil {
		return err
	}
	if reconcileOnly && !run.NeedsReconcile {
		fmt.Fprintf(stdout, "Process run %s does not need reconciliation (action=%s).\n", run.ID, run.Action)
		return nil
	}
	printProcessRun(stdout, run)
	return nil
}

func processResumeCmd() *cobra.Command {
	return processRunMutationCmd("resume", "Resume or tick one runnable process run", "/resume")
}

func processReissueCmd() *cobra.Command {
	return processRunMutationCmd("reissue", "Explicitly reissue a cold outstanding program command", "/reissue")
}

type processRunMutationParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func processRunMutationCmd(use, short, suffix string) *cobra.Command {
	return boa.CmdT[processRunMutationParams]{
		Use: use, Short: short, ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processRunMutationParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessMutation(p, suffix, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessMutation(p *processRunMutationParams, suffix string, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	var response struct {
		Started bool           `json:"started"`
		Run     processRunJSON `json:"run"`
	}
	path := "/v1/process/runs/" + url.PathEscape(strings.TrimSpace(p.RunID)) + suffix
	if err := agent.DaemonRequest(http.MethodPost, path, map[string]any{}, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Process run %s: started=%t\n", response.Run.ID, response.Started)
	printProcessRun(stdout, &response.Run)
	return nil
}

type processRecordOutcomeParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	Outcome  string `long:"outcome" help:"Operator-supplied outcome: succeeded or failed"`
	ExitCode int    `long:"exit-code" optional:"true" help:"Observed program exit code"`
	Error    string `long:"error" optional:"true" help:"Observed failure text"`
	Note     string `long:"note" optional:"true" help:"Operator reconciliation note"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func processRecordOutcomeCmd() *cobra.Command {
	return boa.CmdT[processRecordOutcomeParams]{
		Use:         "record-outcome",
		Short:       "Record an operator-supplied outcome for a cold outstanding command",
		ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processRecordOutcomeParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessRecordOutcome(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessRecordOutcome(p *processRecordOutcomeParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	outcome := engine.ProgramOutcome(strings.TrimSpace(p.Outcome))
	if outcome != engine.ProgramSucceeded && outcome != engine.ProgramFailed {
		return fmt.Errorf("--outcome must be succeeded or failed")
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	request := struct {
		Outcome  engine.ProgramOutcome `json:"outcome"`
		ExitCode int                   `json:"exitCode"`
		Error    string                `json:"error,omitempty"`
		Note     string                `json:"note,omitempty"`
	}{Outcome: outcome, ExitCode: p.ExitCode, Error: p.Error, Note: p.Note}
	var response struct {
		Started bool           `json:"started"`
		Run     processRunJSON `json:"run"`
	}
	path := "/v1/process/runs/" + url.PathEscape(strings.TrimSpace(p.RunID)) + "/record-outcome"
	if err := agent.DaemonRequest(http.MethodPost, path, request, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Recorded outcome for process run %s.\n", response.Run.ID)
	printProcessRun(stdout, &response.Run)
	return nil
}

func fetchProcessRun(runID string, stderr io.Writer) (*processRunJSON, error) {
	runID = strings.TrimSpace(runID)
	if runID == "" {
		return nil, fmt.Errorf("run id is required")
	}
	var run processRunJSON
	if err := agent.DaemonRequest(http.MethodGet, "/v1/process/runs/"+url.PathEscape(runID), nil, &run,
		agent.DaemonOpts{RetryOutput: stderr}); err != nil {
		return nil, err
	}
	return &run, nil
}

func parseProcessParams(values []string) (map[string]string, error) {
	params := make(map[string]string, len(values))
	for _, value := range values {
		key, param, ok := strings.Cut(value, "=")
		key = strings.TrimSpace(key)
		if !ok || key == "" {
			return nil, fmt.Errorf("--param %q must be key=value", value)
		}
		if _, exists := params[key]; exists {
			return nil, fmt.Errorf("--param repeats key %q", key)
		}
		params[key] = param
	}
	return params, nil
}

func requireProcessRuntime(stderr io.Writer) error {
	if err := requireProcessesEnabled(); err != nil {
		return err
	}
	if agent.RequireDaemonOrExit(stderr) != 0 {
		return errProcessDaemonAlreadyReported
	}
	return nil
}

func printProcessRun(out io.Writer, run *processRunJSON) {
	fmt.Fprintf(out, "id=%s\ntemplate=%s\nstatus=%s\naction=%s\nstateVersion=%d\n",
		run.ID, run.TemplateRef, run.Status, run.Action, run.StateVersion)
	if run.NeedsReconcile && run.Checkpoint.OutstandingCommand != nil {
		command := run.Checkpoint.OutstandingCommand
		fmt.Fprintf(out, "needsReconcile=true\ncommand=%s\nnode=%s\nprofile=%s\nprogram=%s\n",
			command.ID, command.NodeID, command.Program.Profile, command.Program.Run)
	}
}

func exitProcessRuntime(err error, stderr io.Writer) {
	if err == nil {
		return
	}
	if !errors.Is(err, errProcessDaemonAlreadyReported) {
		fmt.Fprintf(stderr, "Error: %v\n", err)
	}
	os.Exit(1)
}
