package processcmd

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"slices"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/GiGurra/boa/pkg/boa"
	"github.com/spf13/cobra"
	"github.com/tofutools/tclaude/pkg/claude/agent"
	"github.com/tofutools/tclaude/pkg/claude/process/engine"
	"github.com/tofutools/tclaude/pkg/common"
)

const (
	defaultProcessEventPayloadDisplayBytes = 120
	processEventPageMax                    = 16
	maxProcessEventPayloadDisplayBytes     = 512
	// processCommandNeedsReconcile mirrors the daemon's per-command state
	// label; the CLI keys on it to offer the right next action.
	processCommandNeedsReconcile = "needs_reconcile"
)

var errProcessDaemonAlreadyReported = errors.New("daemon requirement already reported")

type processRunJSON struct {
	ID                    string                   `json:"id"`
	TemplateRef           string                   `json:"templateRef"`
	Params                map[string]string        `json:"params"`
	ProgramAuthorizations []string                 `json:"programAuthorizations"`
	Status                engine.RunStatus         `json:"status"`
	StateVersion          int64                    `json:"stateVersion"`
	Checkpoint            engine.Checkpoint        `json:"checkpoint"`
	Action                string                   `json:"action"`
	NeedsReconcile        bool                     `json:"needsReconcile"`
	AwaitingDecision      *processRunDecisionJSON  `json:"awaitingDecision,omitempty"`
	AwaitingDecisions     []processRunDecisionJSON `json:"awaitingDecisions"`
	Commands              []processRunCommandJSON  `json:"commands"`
	Blocked               []processRunBlockedJSON  `json:"blocked"`
	CreatedAt             time.Time                `json:"createdAt"`
	UpdatedAt             time.Time                `json:"updatedAt"`
}

// processRunDecisionJSON mirrors the daemon's awaited-decision view. Attempt is
// present only for a recurring plan-approval gate, whose window reopens once per
// human rework; an authored decision opens exactly once and reports zero.
type processRunDecisionJSON struct {
	NodeID   string   `json:"nodeId"`
	Verdicts []string `json:"verdicts"`
	// omitempty mirrors the daemon's own tag deliberately: --json decodes this
	// view and re-encodes it, so a plain tag would put "attempt":0 back onto every
	// ordinary authored decision the daemon had omitted it from.
	Attempt int `json:"attempt,omitempty"`
}

type processRunBlockedJSON struct {
	NodeID  string `json:"nodeId"`
	Attempt int    `json:"attempt"`
	Reason  string `json:"reason"`
}

type processRunCommandJSON struct {
	CommandID string `json:"commandId"`
	NodeID    string `json:"nodeId"`
	Profile   string `json:"profile"`
	Program   string `json:"program"`
	State     string `json:"state"`
}

type processRunSummaryJSON struct {
	ID           string           `json:"id"`
	TemplateRef  string           `json:"templateRef"`
	Status       engine.RunStatus `json:"status"`
	StateVersion int64            `json:"stateVersion"`
	CreatedAt    time.Time        `json:"createdAt"`
	UpdatedAt    time.Time        `json:"updatedAt"`
}

type processRunEventJSON struct {
	Sequence   int64           `json:"sequence"`
	OccurredAt time.Time       `json:"occurredAt"`
	NodeID     string          `json:"nodeId"`
	Kind       string          `json:"kind"`
	Payload    json.RawMessage `json:"payload"`
	Actor      string          `json:"actor"`
}

type processRunParams struct {
	TemplateID string   `pos:"true" help:"Saved process-template id to instantiate"`
	RunID      string   `long:"run-id" optional:"true" help:"Explicit run id (normally generated by agentd)"`
	Params     []string `long:"param" optional:"true"`
	Authorize  []string `long:"authorize-program-profile" optional:"true"`
	AskHuman   string   `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func processRunCmd() *cobra.Command {
	return boa.CmdT[processRunParams]{
		Use:         "run",
		Short:       "Instantiate and run the saved template head through agentd",
		Long:        "Pins the exact saved template head and initial checkpoint transactionally. Repeat --param key=value and --authorize-program-profile profile for every exact program profile the run may execute. Use --authorize-program-profile= to explicitly authorize an empty profile.",
		ParamEnrich: common.DefaultParamEnricher(),
		InitFuncCtx: func(ctx *boa.HookContext, p *processRunParams, cmd *cobra.Command) error {
			boa.GetParamT(ctx, &p.Params).SetNoFlag(true)
			cmd.Flags().StringArrayVar(&p.Params, "param", nil, "Template parameter key=value. Repeatable; values may contain commas or '='.")
			boa.GetParamT(ctx, &p.Authorize).SetNoFlag(true)
			cmd.Flags().StringArrayVar(&p.Authorize, "authorize-program-profile", nil, "Explicitly authorize one exact program profile for this run. Repeatable.")
			return nil
		},
		RunFunc: func(p *processRunParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessRun(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessRun(p *processRunParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	params, err := parseProcessParams(p.Params)
	if err != nil {
		return err
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	request := struct {
		ID                       string            `json:"id,omitempty"`
		TemplateID               string            `json:"templateId"`
		Params                   map[string]string `json:"params"`
		AuthorizeProgramProfiles []string          `json:"authorizeProgramProfiles"`
	}{
		ID: strings.TrimSpace(p.RunID), TemplateID: strings.TrimSpace(p.TemplateID),
		Params: params, AuthorizeProgramProfiles: append([]string(nil), p.Authorize...),
	}
	if request.TemplateID == "" {
		return fmt.Errorf("template id is required")
	}
	var run processRunJSON
	if err := agent.DaemonRequest(http.MethodPost, "/v1/process/runs", request, &run,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Created process run %s\n", run.ID)
	printProcessRun(stdout, &run)
	fmt.Fprintf(stdout, "Next: tclaude process show %s; tclaude process events %s\n", run.ID, run.ID)
	return nil
}

type processRunsLsParams struct {
	After    string `long:"after" optional:"true" help:"Exclusive run-id cursor"`
	Limit    int    `long:"limit" optional:"true" help:"Maximum rows (1..32)"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout (for example 30s). Capped at 300s; timeout means deny."`
}

func processRunsLsCmd() *cobra.Command {
	return boa.CmdT[processRunsLsParams]{
		Use:         "ls",
		Short:       "List daemon-owned process runs",
		ParamEnrich: common.DefaultParamEnricher(),
		InitFuncCtx: func(ctx *boa.HookContext, p *processRunsLsParams, _ *cobra.Command) error {
			boa.GetParamT(ctx, &p.AskHuman).SetAlternativesFunc(completeAskHumanDurations)
			return nil
		},
		RunFunc: func(p *processRunsLsParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessRunsLs(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessRunsLs(p *processRunsLsParams, stdout, stderr io.Writer) error {
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	query := url.Values{}
	if after := strings.TrimSpace(p.After); after != "" {
		query.Set("after", after)
	}
	if p.Limit != 0 {
		if p.Limit < 1 || p.Limit > 32 {
			return fmt.Errorf("--limit must be 1..32")
		}
		query.Set("limit", strconv.Itoa(p.Limit))
	}
	path := "/v1/process/runs"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var response struct {
		Runs []processRunSummaryJSON `json:"runs"`
		Next string                  `json:"next"`
	}
	if err := agent.DaemonRequest(http.MethodGet, path, nil, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	if len(response.Runs) == 0 {
		fmt.Fprintln(stdout, "No process runs.")
		return nil
	}
	tw := newTable(stdout)
	fmt.Fprintln(tw, "ID\tTEMPLATE\tSTATUS\tUPDATED")
	for _, run := range response.Runs {
		fmt.Fprintf(tw, "%s\t%s\t%s\t%s\n", run.ID, run.TemplateRef, run.Status, formatTime(run.UpdatedAt))
	}
	if err := tw.Flush(); err != nil {
		return err
	}
	if response.Next != "" {
		fmt.Fprintf(stdout, "next=%s\n", response.Next)
	}
	return nil
}

type processRunIDParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout (for example 30s). Capped at 300s; timeout means deny."`
}

type processShowParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	JSON     bool   `long:"json" help:"Output the complete run snapshot as JSON"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout (for example 30s). Capped at 300s; timeout means deny."`
}

func processShowCmd() *cobra.Command {
	return boa.CmdT[processShowParams]{
		Use: "show", Short: "Show one daemon-owned process run",
		ParamEnrich: common.DefaultParamEnricher(),
		InitFuncCtx: func(ctx *boa.HookContext, p *processShowParams, _ *cobra.Command) error {
			boa.GetParamT(ctx, &p.AskHuman).SetAlternativesFunc(completeAskHumanDurations)
			return nil
		},
		RunFunc: func(p *processShowParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessShow(p.RunID, p.AskHuman, false, p.JSON, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

type processEventsParams struct {
	RunID        string `pos:"true" help:"Process run id"`
	After        int64  `long:"after" optional:"true" help:"Exclusive event-sequence cursor"`
	Limit        int    `long:"limit" optional:"true" default:"16" help:"Maximum rows (1..16)"`
	JSON         bool   `long:"json" help:"Output the complete event page as JSON"`
	JSONLines    bool   `long:"json-lines" help:"Output one event object per line"`
	PayloadBytes int    `long:"payload-bytes" default:"120" help:"Table payload preview bytes (0 hides the column; maximum 512)"`
	AskHuman     string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout (for example 30s). Capped at 300s; timeout means deny."`
}

func processEventsCmd() *cobra.Command {
	return boa.CmdT[processEventsParams]{
		Use:         "events",
		Short:       "Show ordered human-facing evidence for one process run",
		ParamEnrich: common.DefaultParamEnricher(),
		InitFuncCtx: func(ctx *boa.HookContext, p *processEventsParams, _ *cobra.Command) error {
			boa.GetParamT(ctx, &p.AskHuman).SetAlternativesFunc(completeAskHumanDurations)
			return nil
		},
		RunFunc: func(p *processEventsParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessEvents(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessEvents(p *processEventsParams, stdout, stderr io.Writer) error {
	runID := strings.TrimSpace(p.RunID)
	if runID == "" {
		return fmt.Errorf("run id is required")
	}
	if p.JSON && p.JSONLines {
		return fmt.Errorf("--json and --json-lines are mutually exclusive")
	}
	if (p.JSON || p.JSONLines) && p.PayloadBytes != defaultProcessEventPayloadDisplayBytes {
		return fmt.Errorf("--payload-bytes is only valid for table output")
	}
	if p.After < 0 {
		return fmt.Errorf("--after must be a non-negative sequence")
	}
	if p.Limit < 1 || p.Limit > processEventPageMax {
		return fmt.Errorf("--limit must be 1..%d", processEventPageMax)
	}
	if p.PayloadBytes < 0 || p.PayloadBytes > maxProcessEventPayloadDisplayBytes {
		return fmt.Errorf("--payload-bytes must be 0..%d", maxProcessEventPayloadDisplayBytes)
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	query := url.Values{}
	if p.After != 0 {
		query.Set("after", strconv.FormatInt(p.After, 10))
	}
	query.Set("limit", strconv.Itoa(p.Limit))
	path := "/v1/process/runs/" + url.PathEscape(runID) + "/events"
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	var response struct {
		Events []processRunEventJSON `json:"events"`
		Next   int64                 `json:"next"`
	}
	if err := agent.DaemonRequest(http.MethodGet, path, nil, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	if p.JSON {
		return json.NewEncoder(stdout).Encode(response)
	}
	if p.JSONLines {
		encoder := json.NewEncoder(stdout)
		for i := range response.Events {
			if err := encoder.Encode(response.Events[i]); err != nil {
				return err
			}
		}
		return nil
	}
	if len(response.Events) == 0 {
		if p.After == 0 {
			fmt.Fprintf(stdout, "No evidence recorded for process run %s.\n", runID)
		} else {
			fmt.Fprintf(stdout, "No evidence after sequence %d for process run %s.\n", p.After, runID)
		}
		return nil
	}
	tw := newTable(stdout)
	if p.PayloadBytes == 0 {
		fmt.Fprintln(tw, "SEQ\tTIME\tNODE\tKIND\tACTOR")
	} else {
		fmt.Fprintln(tw, "SEQ\tTIME\tNODE\tKIND\tACTOR\tPAYLOAD")
	}
	for _, event := range response.Events {
		fmt.Fprintf(tw, "%d\t%s\t%s\t%s\t%s",
			event.Sequence, formatTime(event.OccurredAt), displayProcessEventField(event.NodeID),
			event.Kind, displayProcessEventField(event.Actor))
		if p.PayloadBytes > 0 {
			fmt.Fprintf(tw, "\t%s", formatProcessEventPayload(event.Payload, p.PayloadBytes))
		}
		fmt.Fprintln(tw)
	}
	if err := tw.Flush(); err != nil {
		return err
	}
	if response.Next != 0 {
		fmt.Fprintf(stdout, "next=%d\n", response.Next)
	}
	return nil
}

func displayProcessEventField(value string) string {
	if value == "" {
		return "-"
	}
	return value
}

func formatProcessEventPayload(payload json.RawMessage, maxBytes int) string {
	var compact bytes.Buffer
	if err := json.Compact(&compact, payload); err != nil {
		return "<invalid JSON>"
	}
	value := compact.String()
	if len(value) <= maxBytes {
		return value
	}
	ellipsis := "..."
	if maxBytes < len(ellipsis) {
		ellipsis = ellipsis[:maxBytes]
	}
	cut := maxBytes - len(ellipsis)
	for cut > 0 && !utf8.ValidString(value[:cut]) {
		cut--
	}
	return value[:cut] + ellipsis
}

func processReconcileCmd() *cobra.Command {
	return processRunReadCmd("reconcile", "Inspect whether a run needs explicit reconciliation", true)
}

func processRunReadCmd(use, short string, reconcileOnly bool) *cobra.Command {
	return boa.CmdT[processRunIDParams]{
		Use: use, Short: short, ParamEnrich: common.DefaultParamEnricher(),
		InitFuncCtx: func(ctx *boa.HookContext, p *processRunIDParams, _ *cobra.Command) error {
			boa.GetParamT(ctx, &p.AskHuman).SetAlternativesFunc(completeAskHumanDurations)
			return nil
		},
		RunFunc: func(p *processRunIDParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessShow(p.RunID, p.AskHuman, reconcileOnly, false, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessShow(runID, askHuman string, reconcileOnly, jsonOutput bool, stdout, stderr io.Writer) error {
	ask, err := agent.ParseAskHuman(askHuman)
	if err != nil {
		return err
	}
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	run, err := fetchProcessRun(runID, ask, stderr)
	if err != nil {
		return err
	}
	if jsonOutput {
		return json.NewEncoder(stdout).Encode(run)
	}
	if reconcileOnly && !run.NeedsReconcile {
		fmt.Fprintf(stdout, "Process run %s does not need reconciliation (action=%s).\n", run.ID, run.Action)
		return nil
	}
	printProcessRun(stdout, run)
	return nil
}

func processResumeCmd() *cobra.Command {
	return boa.CmdT[processRunMutationParams]{
		Use: "resume", Short: "Resume or tick one runnable process run",
		ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processRunMutationParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessMutation(p, "/resume", nil, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func processReissueCmd() *cobra.Command {
	return boa.CmdT[processReissueParams]{
		Use:   "reissue",
		Short: "Explicitly reissue a cold outstanding program command",
		Long: "Records an explicit operator retry for one outstanding command. " +
			"A run can hold several at once, so --node is required unless exactly one command needs reconciliation.",
		ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processReissueParams, _ *cobra.Command, _ []string) {
			request := map[string]any{}
			if node := strings.TrimSpace(p.Node); node != "" {
				request["nodeId"] = node
			}
			exitProcessRuntime(runProcessMutation(&processRunMutationParams{
				RunID: p.RunID, AskHuman: p.AskHuman,
			}, "/reissue", request, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

type processRunMutationParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

type processReissueParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	Node     string `long:"node" optional:"true" help:"Node id of the outstanding command to reissue; required when more than one needs reconciliation"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func runProcessMutation(p *processRunMutationParams, suffix string, request map[string]any, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	if request == nil {
		request = map[string]any{}
	}
	var response struct {
		Started bool           `json:"started"`
		Run     processRunJSON `json:"run"`
	}
	path := "/v1/process/runs/" + url.PathEscape(strings.TrimSpace(p.RunID)) + suffix
	if err := agent.DaemonRequest(http.MethodPost, path, request, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Process run %s: started=%t\n", response.Run.ID, response.Started)
	printProcessRun(stdout, &response.Run)
	return nil
}

type processRecordOutcomeParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	Node     string `long:"node" optional:"true" help:"Node id of the outstanding command; required when more than one needs reconciliation"`
	Outcome  string `long:"outcome" help:"Operator-supplied outcome: succeeded or failed"`
	ExitCode int    `long:"exit-code" optional:"true" help:"Observed program exit code"`
	Error    string `long:"error" optional:"true" help:"Observed failure text"`
	Note     string `long:"note" optional:"true" help:"Operator reconciliation note"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func processRecordOutcomeCmd() *cobra.Command {
	return boa.CmdT[processRecordOutcomeParams]{
		Use:         "record-outcome",
		Short:       "Record an operator-supplied outcome for a cold outstanding command",
		ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processRecordOutcomeParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessRecordOutcome(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessRecordOutcome(p *processRecordOutcomeParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	outcome := engine.ProgramOutcome(strings.TrimSpace(p.Outcome))
	if outcome != engine.ProgramSucceeded && outcome != engine.ProgramFailed {
		return fmt.Errorf("--outcome must be succeeded or failed")
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	request := struct {
		NodeID   string                `json:"nodeId,omitempty"`
		Outcome  engine.ProgramOutcome `json:"outcome"`
		ExitCode int                   `json:"exitCode"`
		Error    string                `json:"error,omitempty"`
		Note     string                `json:"note,omitempty"`
	}{NodeID: strings.TrimSpace(p.Node), Outcome: outcome, ExitCode: p.ExitCode, Error: p.Error, Note: p.Note}
	var response struct {
		Started bool           `json:"started"`
		Run     processRunJSON `json:"run"`
	}
	path := "/v1/process/runs/" + url.PathEscape(strings.TrimSpace(p.RunID)) + "/record-outcome"
	if err := agent.DaemonRequest(http.MethodPost, path, request, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Recorded outcome for process run %s.\n", response.Run.ID)
	printProcessRun(stdout, &response.Run)
	return nil
}

type processDecideParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	Node     string `long:"node" help:"Awaited decision node id"`
	Verdict  string `long:"verdict" help:"Authored outcome label to select"`
	Evidence string `long:"evidence" optional:"true" help:"Human-facing evidence recorded with the decision"`
	Attempt  int    `long:"attempt" optional:"true" help:"Exact approval window from tclaude process show; only a plan-approval gate has one"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func processDecideCmd() *cobra.Command {
	return boa.CmdT[processDecideParams]{
		Use:         "decide",
		Short:       "Record a manual verdict for the run's awaited decision node",
		Long: "Selects exactly one authored outcome edge of the awaited decision node and closes every alternative. " +
			"A compound's plan-approval gate is decided the same way, with approve readying the do stage and rework " +
			"sending the plan back for one more run; because that window reopens, its verdict must also name the exact " +
			"--attempt tclaude process show reports. Duplicate, stale, wrong-node, and wrong-attempt input is refused.",
		ParamEnrich: common.DefaultParamEnricher(),
		RunFunc: func(p *processDecideParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessDecide(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

func runProcessDecide(p *processDecideParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	node := strings.TrimSpace(p.Node)
	if node == "" {
		return fmt.Errorf("--node is required")
	}
	if p.Verdict == "" {
		return fmt.Errorf("--verdict is required")
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	request := struct {
		NodeID   string `json:"nodeId"`
		Verdict  string `json:"verdict"`
		Evidence string `json:"evidence,omitempty"`
		Attempt  int    `json:"attempt,omitempty"`
	}{NodeID: node, Verdict: p.Verdict, Evidence: p.Evidence, Attempt: p.Attempt}
	var response struct {
		Started bool           `json:"started"`
		Run     processRunJSON `json:"run"`
	}
	path := "/v1/process/runs/" + url.PathEscape(strings.TrimSpace(p.RunID)) + "/decide"
	if err := agent.DaemonRequest(http.MethodPost, path, request, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Recorded decision %q for process run %s.\n", p.Verdict, response.Run.ID)
	printProcessRun(stdout, &response.Run)
	return nil
}

type processResolveBlockedParams struct {
	RunID    string `pos:"true" help:"Process run id"`
	Node     string `long:"node" help:"Blocked node id"`
	Attempt  int    `long:"attempt" help:"Exact attempt the node is blocked at, from tclaude process show"`
	Action   string `long:"action" help:"retry, skip, or cancel"`
	Note     string `long:"note" optional:"true" help:"Human-facing note recorded with the resolution"`
	AskHuman string `long:"ask-human" optional:"true" help:"On permission denial, ask the human via popup with this timeout"`
}

func processResolveBlockedCmd() *cobra.Command {
	return boa.CmdT[processResolveBlockedParams]{
		Use:   "resolve-blocked",
		Short: "Retry, skip, or cancel a branch parked by an exhausted retry budget",
		Long: "Resolves one blocked branch, bound to the exact node and attempt tclaude process show reports. " +
			"retry opens one fresh authored-size attempt window without reusing an attempt number; " +
			"skip settles the task through its authored route and activates downstream work; " +
			"cancel gives up on the run, which drains its in-flight programs and finishes canceled. " +
			"Duplicate, stale, wrong-node, and wrong-attempt input is refused.",
		ParamEnrich: common.DefaultParamEnricher(),
		InitFuncCtx: func(ctx *boa.HookContext, p *processResolveBlockedParams, _ *cobra.Command) error {
			boa.GetParamT(ctx, &p.Action).SetAlternatives(processResolutionActions)
			boa.GetParamT(ctx, &p.AskHuman).SetAlternativesFunc(completeAskHumanDurations)
			return nil
		},
		RunFunc: func(p *processResolveBlockedParams, _ *cobra.Command, _ []string) {
			exitProcessRuntime(runProcessResolveBlocked(p, os.Stdout, os.Stderr), os.Stderr)
		},
	}.ToCobra()
}

var processResolutionActions = []string{
	string(engine.ResolveRetry), string(engine.ResolveSkip), string(engine.ResolveCancel),
}

// runProcessResolveBlocked validates in the same order the other run verbs do:
// the daemon requirement first, then this command's own arguments, so a
// malformed invocation never depends on whether agentd happens to be up.
func runProcessResolveBlocked(p *processResolveBlockedParams, stdout, stderr io.Writer) error {
	if err := requireProcessRuntime(stderr); err != nil {
		return err
	}
	node := strings.TrimSpace(p.Node)
	if node == "" {
		return fmt.Errorf("--node is required")
	}
	if p.Attempt < 1 {
		return fmt.Errorf("--attempt must be the exact attempt the node is blocked at")
	}
	action := engine.ResolutionAction(strings.TrimSpace(p.Action))
	if !slices.Contains(processResolutionActions, string(action)) {
		return fmt.Errorf("--action must be %s", strings.Join(processResolutionActions, ", "))
	}
	ask, err := agent.ParseAskHuman(p.AskHuman)
	if err != nil {
		return err
	}
	request := struct {
		NodeID  string                  `json:"nodeId"`
		Attempt int                     `json:"attempt"`
		Action  engine.ResolutionAction `json:"action"`
		Note    string                  `json:"note,omitempty"`
	}{NodeID: node, Attempt: p.Attempt, Action: action, Note: p.Note}
	var response struct {
		Started bool           `json:"started"`
		Run     processRunJSON `json:"run"`
	}
	path := "/v1/process/runs/" + url.PathEscape(strings.TrimSpace(p.RunID)) + "/resolve-blocked"
	if err := agent.DaemonRequest(http.MethodPost, path, request, &response,
		agent.DaemonOpts{AskHuman: ask, RetryOutput: stderr}); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Resolved blocked node %s attempt %d with %s for process run %s.\n",
		node, p.Attempt, action, response.Run.ID)
	printProcessRun(stdout, &response.Run)
	return nil
}

func fetchProcessRun(runID string, askHuman time.Duration, stderr io.Writer) (*processRunJSON, error) {
	runID = strings.TrimSpace(runID)
	if runID == "" {
		return nil, fmt.Errorf("run id is required")
	}
	var run processRunJSON
	if err := agent.DaemonRequest(http.MethodGet, "/v1/process/runs/"+url.PathEscape(runID), nil, &run,
		agent.DaemonOpts{AskHuman: askHuman, RetryOutput: stderr}); err != nil {
		return nil, err
	}
	return &run, nil
}

// completeAskHumanDurations mirrors the agent command completion hints. The
// flag accepts any valid duration, so these are suggestions rather than a
// strict allow-list.
func completeAskHumanDurations(_ *cobra.Command, _ []string, toComplete string) []string {
	suggestions := []string{"15s", "30s", "60s", "2m", "5m"}
	var matches []string
	for _, suggestion := range suggestions {
		if strings.HasPrefix(suggestion, toComplete) {
			matches = append(matches, suggestion)
		}
	}
	return matches
}

func parseProcessParams(values []string) (map[string]string, error) {
	params := make(map[string]string, len(values))
	for _, value := range values {
		key, param, ok := strings.Cut(value, "=")
		key = strings.TrimSpace(key)
		if !ok || key == "" {
			return nil, fmt.Errorf("--param %q must be key=value", value)
		}
		if _, exists := params[key]; exists {
			return nil, fmt.Errorf("--param repeats key %q", key)
		}
		params[key] = param
	}
	return params, nil
}

// requireProcessRuntime is the precondition for every daemon-owned process
// command: only that agentd is reachable. The feature flag itself is NOT
// checked here — agentd is the sole authority and each process route returns a
// stable {code:"processes_disabled"} response when the flag is off. Reading the
// flag client-side previously loaded private config as defaults and wrongly
// blocked sandboxed agents that legitimately could reach an enabled daemon.
func requireProcessRuntime(stderr io.Writer) error {
	if agent.RequireDaemonOrExit(stderr) != 0 {
		return errProcessDaemonAlreadyReported
	}
	return nil
}

// printProcessRun renders the run's header plus both plural outboxes. A run
// under bounded concurrency can hold several commands and several awaited
// decisions at once, and each of them is separately addressable, so each gets
// its own row rather than one line standing in for all of them.
func printProcessRun(out io.Writer, run *processRunJSON) {
	fmt.Fprintf(out, "id=%s\ntemplate=%s\nstatus=%s\naction=%s\nstateVersion=%d\n",
		run.ID, run.TemplateRef, run.Status, run.Action, run.StateVersion)
	if run.NeedsReconcile {
		fmt.Fprintln(out, "needsReconcile=true")
	}
	if len(run.Commands) > 0 {
		fmt.Fprintln(out, "commands:")
		tw := newTable(out)
		fmt.Fprintln(tw, "NODE\tSTATE\tPROFILE\tPROGRAM\tCOMMAND")
		for _, command := range run.Commands {
			fmt.Fprintf(tw, "%s\t%s\t%s\t%s\t%s\n", command.NodeID, command.State,
				displayProcessEventField(command.Profile), command.Program, command.CommandID)
		}
		_ = tw.Flush()
	}
	if len(run.Blocked) > 0 {
		fmt.Fprintln(out, "blocked:")
		tw := newTable(out)
		fmt.Fprintln(tw, "NODE\tATTEMPT\tREASON")
		for _, blocked := range run.Blocked {
			fmt.Fprintf(tw, "%s\t%d\t%s\n", blocked.NodeID, blocked.Attempt,
				displayProcessEventField(blocked.Reason))
		}
		_ = tw.Flush()
	}
	if len(run.AwaitingDecisions) > 0 {
		fmt.Fprintln(out, "awaitingDecisions:")
		tw := newTable(out)
		fmt.Fprintln(tw, "NODE\tVERDICTS")
		for _, decision := range run.AwaitingDecisions {
			fmt.Fprintf(tw, "%s\t%s\n", decision.NodeID, strings.Join(decision.Verdicts, ", "))
		}
		_ = tw.Flush()
	}
	printProcessRunNextSteps(out, run)
}

// printProcessRunNextSteps names the exact command the operator would run next.
// With more than one candidate the selector is mandatory, so the hint carries
// it rather than suggesting an invocation that would be refused as ambiguous.
func printProcessRunNextSteps(out io.Writer, run *processRunJSON) {
	var ambiguous []string
	for _, command := range run.Commands {
		if command.State == processCommandNeedsReconcile {
			ambiguous = append(ambiguous, command.NodeID)
		}
	}
	switch {
	case len(ambiguous) == 1:
		fmt.Fprintf(out, "Next: tclaude process reissue %s; tclaude process record-outcome %s --outcome <succeeded|failed>\n",
			run.ID, run.ID)
	case len(ambiguous) > 1:
		fmt.Fprintf(out, "Next: name one of %s, for example tclaude process reissue %s --node %s\n",
			strings.Join(ambiguous, ", "), run.ID, ambiguous[0])
	}
	// A recurring approval window is part of the decision's identity, so its hint
	// carries the exact one rather than an invocation the daemon would refuse as
	// stale. An authored decision opens once, reports zero, and keeps the command
	// it has always had.
	for _, decision := range run.AwaitingDecisions {
		if decision.Attempt > 0 {
			fmt.Fprintf(out, "Next: tclaude process decide %s --node %s --attempt %d --verdict <verdict>\n",
				run.ID, decision.NodeID, decision.Attempt)
			continue
		}
		fmt.Fprintf(out, "Next: tclaude process decide %s --node %s --verdict <verdict>\n",
			run.ID, decision.NodeID)
	}
	// The attempt is part of the blocked identity, so the hint carries the exact
	// one rather than an invocation the daemon would refuse as stale.
	for _, blocked := range run.Blocked {
		fmt.Fprintf(out, "Next: tclaude process resolve-blocked %s --node %s --attempt %d --action <%s>\n",
			run.ID, blocked.NodeID, blocked.Attempt, strings.Join(processResolutionActions, "|"))
	}
}

func exitProcessRuntime(err error, stderr io.Writer) {
	if err == nil {
		return
	}
	if !errors.Is(err, errProcessDaemonAlreadyReported) {
		fmt.Fprintf(stderr, "Error: %v\n", err)
	}
	os.Exit(1)
}
